### PR TITLE
F#479 the preview will always be shown 

### PR DESCRIPTION
**Pull request by ksparknot**
### Description
if the preview directory is missing, we need to make new preview files
when user requests dataset(JPA), if there is no preview, 
1. imported dataset -> create new preview file
2. wrangled dataset -> show a message that says 'try to edit rules' -> transform stage makes new preview 

**Related Issue** : 
[#479](https://github.com/metatron-app/metatron-discovery/issues/479)

### How Has This Been Tested?
1. make a dataset what is imported type or wrangled type
2. see the details of the dataset. there is a preview
3. delete a preview files where is in preview directory
4. see the details of the dataset again. there is still a preview. the preview is new one.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ksparknot** [comment]
run build
deploy to 2

**Comment by joohokim1** [comment]
There seems to be much more coding to do. I will close PR without merge once.

_꽤 더 코딩할 내용이 있어보입니다. 일단 PR은 merge 없이 닫겠습니다._

**Comment by ksparknot** [comment]
Issue 1.
when client requests dataset with grid-response
server should respond a grid-response on time

Issue 2.
dataset with grid and without grid should be distinguished when getting JPA entity


It is complicated
so this time i will merge the code
the issues will be handled later.

**Comment by ksparknot** [comment]
Issue 1.
when client requests dataset with grid-response
server should respond a grid-response on time

Issue 2.
dataset with grid and without grid should be distinguished when getting JPA entity


It is complicated
so this time i will merge the code
the issues will be handled later.

**Comment by ksparknot** [comment]
Issue 1.
when client requests dataset with grid-response
server should respond a grid-response on time

Issue 2.
dataset with grid and without grid should be distinguished when getting JPA entity


It is complicated
so this time i will merge the code
the issues will be handled later.

**Comment by ksparknot** [comment]
Issue 1.
when client requests dataset with grid-response
server should respond a grid-response on time

Issue 2.
dataset with grid and without grid should be distinguished when getting JPA entity


It is complicated
so this time i will merge the code
the issues will be handled later.

**Comment by ksparknot** [comment]
Issue 1.
when client requests dataset with grid-response
server should respond a grid-response on time

Issue 2.
dataset with grid and without grid should be distinguished when getting JPA entity


It is complicated
so this time i will merge the code
the issues will be handled later.

**Comment by ksparknot** [comment]
Issue 1.
when client requests dataset with grid-response
server should respond a grid-response on time

Issue 2.
dataset with grid and without grid should be distinguished when getting JPA entity


It is complicated
so this time i will merge the code
the issues will be handled later.

**Comment by ksparknot** [comment]
Issue 1.
when client requests dataset with grid-response
server should respond a grid-response on time

Issue 2.
dataset with grid and without grid should be distinguished when getting JPA entity


It is complicated
so this time i will merge the code
the issues will be handled later.

**Comment by ksparknot** [comment]
Issue 1.
when client requests dataset with grid-response
server should respond a grid-response on time

Issue 2.
dataset with grid and without grid should be distinguished when getting JPA entity


It is complicated
so this time i will merge the code
the issues will be handled later.

**Comment by ksparknot** [comment]
Issue 1.
when client requests dataset with grid-response
server should respond a grid-response on time

Issue 2.
dataset with grid and without grid should be distinguished when getting JPA entity


It is complicated
so this time i will merge the code
the issues will be handled later.

**Comment by ksparknot** [comment]
Issue 1.
when client requests dataset with grid-response
server should respond a grid-response on time

Issue 2.
dataset with grid and without grid should be distinguished when getting JPA entity


It is complicated
so this time i will merge the code
the issues will be handled later.

**Comment by ksparknot** [comment]
Issue 1.
when client requests dataset with grid-response
server should respond a grid-response on time

Issue 2.
dataset with grid and without grid should be distinguished when getting JPA entity


It is complicated
so this time i will merge the code
the issues will be handled later.

**Comment by ksparknot** [comment]
Issue 1.
when client requests dataset with grid-response
server should respond a grid-response on time

Issue 2.
dataset with grid and without grid should be distinguished when getting JPA entity


It is complicated
so this time i will merge the code
the issues will be handled later.

**Comment by ksparknot** [comment]
Issue 1.
when client requests dataset with grid-response
server should respond a grid-response on time

Issue 2.
dataset with grid and without grid should be distinguished when getting JPA entity


It is complicated
so this time i will merge the code
the issues will be handled later.

**Comment by ksparknot** [comment]
Issue 1.
when client requests dataset with grid-response
server should respond a grid-response on time

Issue 2.
dataset with grid and without grid should be distinguished when getting JPA entity


It is complicated
so this time i will merge the code
the issues will be handled later.

**Comment by ksparknot** [comment]
Issue 1.
when client requests dataset with grid-response
server should respond a grid-response on time

Issue 2.
dataset with grid and without grid should be distinguished when getting JPA entity


It is complicated
so this time i will merge the code
the issues will be handled later.

**Comment by ksparknot** [comment]
Do not apply because it is unstable

**Pull request closed without merging**
