### PR TITLE
F#1976 snapshot as sql script

### PR DESCRIPTION
**Pull request by ksparknot**
### Description
now, snapshot has a file format for sql

**Related Issue** : 
[1976](https://github.com/metatron-app/metatron-discovery/issues/1976)

### How Has This Been Tested?
1. create a snapshot of file type
2. choose sql for the file format
3. go to the detail page of the snapshot
4. you can download a file of sql

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ksparknot** [comment]
deploy to 2

**Comment by ksparknot** [comment]
deploy to 2

**Comment by ksparknot** [comment]
deploy to 2

**Comment by ksparknot** [comment]
deploy to 2

**Comment by ksparknot** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Pull request merged**
