### PR TITLE
#2894 css change

### PR DESCRIPTION
**Pull request by AnnieHwang**
### Description
Changed the common layout and style around the 'Management' menu. (Especially changed the 'data source' menu)
-Changed the GNB of the creation UI.
-Search filter list screen has been changed.

**Related Issue** : 
#2894

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] My code follows the code style of this project.
- [ x ] My change requires a change to the documentation.
- [ x ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 5

**Comment by ufoscw** [comment]
@AnnieHwang 
1. The Results tab at the bottom of the workbench has disappeared.

2. Column List icon and text error in workbench.
metatron_Discovery

3. connection name disappeared in workbench lnb.
metatron_Discovery

4. Size Error When workbench LNB Folded
metatron_Discovery_및_DevTools_-_localhost_8180_app_v2_exploredata_view

5. Schema browser layer's tab is broken.
metatron_Discovery

6. broken layer position in Management > Exploration.
ex) create new metadata from database, create column disctionary, create code table...
metatron_Discovery_및_DevTools_-_localhost_8180_app_v2_exploredata_view

7. datagrid css broken in Management > Exploration > Column Details
metatron_Discovery

**Comment by minhyun2** [comment]
@AnnieHwang 
1. Datasource - Data tab - data results are not displayed.
DevTools_-_metatron-web-04_8189_app_v2_management_storage_datasource_및_metatron_Discovery

2. Datasource - Column detail tab - css broken.
metatron_Discovery

3. Datasource - Create datasource - Ingestion setting
metatron_Discovery

4. Datasource - Create datasource with stream - Select topic css broken.
metatron_Discovery

5. Datasource - Create datasource with stream - Configure the schema
metatron_Discovery

6. Dataconnection - can not click to enter the detail screen from the list.

7. Engine Monitoring Overview
metatron_Discovery

8. Themes checkbox
metatron_Discovery

**Comment by minhyun2** [comment]
@AnnieHwang 
1. Edit chart lnb search area and column font color
metatron_Discovery

2. Custom column
metatron_Discovery

3. Can not create a new share workspace
shared workspace

4. Can not create a new permission schema
create schema

5. Workspace - Datasource list css broken
metatron_Discovery

**Comment by minhyun2** [comment]
deploy to 5

**Comment by AnnieHwang** [comment]
@minhyun2 Please check the number 4 menu path. Please check how you tested. I couldn't find the button.

**Comment by minhyun2** [comment]
> @minhyun2 Please check the number 4 menu path. Please check how you tested. I couldn't find the button.

@AnnieHwang 
Administration - Workspaces - Permission schemas

**Comment by minhyun2** [comment]
deploy to 5

**Comment by ufoscw** [comment]
deploy to 5

**Comment by ufoscw** [comment]
@AnnieHwang 
It seems that some sources are missing when merging the master branch.
Please check again.

**Comment by minhyun2** [comment]
@AnnieHwang 
1. After resolving conflicts, #2989 is missing.
 - Support an array type of columns
 - There was a new scroll that did not exist in the step of specifying a time-type column.
metatron_Discovery

2. Screen css in workspace datasource list is broken (Filter, Column list)
metatron_Discovery

3. There are two vertical scrolls in Datasource Preview
metatron_Discovery

**Comment by AnnieHwang** [comment]
@minhyun2 @ufoscw The work is finished. Put it on the test server once more.

**Comment by AnnieHwang** [comment]
@ufoscw @minhyun2 Please deploy it to the test server.

**Comment by minhyun2** [comment]
deploy to 5

**Comment by minhyun2** [comment]
deploy to 5

**Pull request closed without merging**
