### PR TITLE
fn-fix_dataprep_dataflow_button

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

Change button design
**Related Issue** : 

METATRON-3005

### How Has This Been Tested?

1.Management -> Data prep -> Data flow -> click root
2. check button is changed
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
스크린샷 2019-09-04 오후 11 23 02

@thinkcsww @eltriny I was just wondering if the work has done. It's not working well as you see. If it's too hard to resolve, please let me know. We could change the design.

**Comment by kyungtaak** [comment]
@joohokim1 I think that you'd rather request this issue to @AnnieHwang than @eltryny

**Comment by thinkcsww** [comment]
@kyungtaak 
image
modified like this

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
@kyungtaak Yes, I'll report to @AnnieHwang, later on.

**Pull request merged**
