### PR TITLE
F#36 save on hdfs first

### PR DESCRIPTION
**Pull request by ksparknot**
### Description
condition.
before: can access to stagingBaseDir
after: stagingBaseDir is specified

**Related Issue** : [#36](https://github.com/metatron-app/metatron-discovery/issues/36) 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by joohokim1** [comment]
run build
deploy to 4

**Comment by joohokim1** [comment]
run build
deploy to 4

**Comment by alchan-lee** [comment]
새로 만든 4번 테스트베드에 문제가 있는것 같습니다..
수리중이니 그동안 우선 3번으로 이용 부탁드려요

**Comment by joohokim1** [comment]
run build
deploy to 3

**Pull request merged**
