### PR TITLE
fix error black theme style

### PR DESCRIPTION
**Pull request by eltriny**
### Description
1. The thumbnail icon of the empty dashboard is changed depending on the selection.
2. Design tooltips and window tooltips pop up at the same time in items in the workspace
3. The data source list layer in the dashboard list does not display correctly.
4. Black theme Legend text is not visible.
5. The explosion title font is incorrect.

**Related Issue** : 

### How Has This Been Tested?
1. Make sure that the Thumbnail icon on the empty dashboard displays well regardless of the selection.
2. Verify that the window tooltips do not appear when the design tooltips are displayed in items in the workspace.
3. Verify that the data source list layer in the dashboard list is displayed normally.
4. Make sure the legend text is visible at the time of the black theme.
5. Check if the explosion title font is normal.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 4

**Comment by ufoscw** [comment]
@eltriny 
Not sure if it's a css modified side effect.
metatron_Discovery

**Comment by minhyun2** [comment]
run build
deploy to 4

**Comment by ufoscw** [comment]
@eltriny 
please resolve conflicts.

**Comment by kyungtaak** [comment]
@eltriny It seem to be critical issue. Is it known issue?
image
image

**Comment by eltriny** [comment]
@kyungtaak 
다시 확인 부탁드립니다. 제쪽에서 확인하기에는 이상없이 잘 나오고 있습니다.
스크린샷 2019-10-04 오후 12 30 50
스크린샷 2019-10-04 오후 12 30 58
스크린샷 2019-10-04 오후 12 31 03

**Comment by ufoscw** [comment]
run build
deploy to 4

**Pull request merged**
