### PR TITLE
Fix NPE for changing datasource in dashboard

### PR DESCRIPTION
**Pull request by minhyun2**
### Description

Fix NPE for changing datasource in dashboard

**Related Issue** : 

### How Has This Been Tested?

1. Create a dashboard with database datasource
2. Create a widget
3. Change the datasource to another database datasource

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Review by ufoscw — APPROVED** [review]

**Pull request merged**
