### PR TITLE
#2605 add filtering, sorting functionality in explore data list

### PR DESCRIPTION
**Pull request by thinkcsww**
add sorting, filtering function in explore-data-list

### Description

sorting by name, popularity, modified time
filtering by source type

**Related Issue** : 

#2605 

### How Has This Been Tested?

1. LNB -> Exploration -> data
2. search something
3. check filtering and sorting works properly
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 5

**Comment by ufoscw** [comment]
@thinkcsww 
1. please use "sort" parameter for sorting list.
Request Sample
```
(GET) /api/metadatas?sort=modified%2Cdesc
```

2. Popularity sort is not currently supported.
Please remove popularity sort function.

3. missed Updated filter
metatron_Discovery

like this
metatron_Discovery

**Comment by thinkcsww** [comment]
@ufoscw 
what is the meaning of 3.missed Updated filter?

**Comment by ufoscw** [comment]
@thinkcsww 
Please add a Filter item. (Updated time)

**Comment by ufoscw** [comment]
run build
deploy to 4

**Comment by ufoscw** [comment]
@thinkcsww 
build error occurred.

```
[INFO] 
[INFO] Date: 2019-09-30T02:37:29.676Z
[INFO] Hash: d49597bcf0e71562f885
[INFO] Time: 43201ms
[INFO] chunk {0} runtime.3323048330809c6e5ed2.js (runtime) 1.42 kB [entry] [rendered]
[INFO] chunk {1} main.5f13b498ec6976cdb0c7.js (main) 128 bytes [initial] [rendered]
[INFO] chunk {2} polyfills.cc3ea7a3070884bdee7e.js (polyfills) 130 bytes [initial] [rendered]
[INFO] chunk {3} styles.747930430657c16cf482.css, styles.f667e6f5c7748ed2f72c.js (styles) 2.58 MB [initial] [rendered]
[INFO] chunk {scripts} scripts.6a95a8dc08eeda08cb73.js (scripts) 5.97 MB [entry] [rendered]
[INFO] 
[INFO] 
[ERROR] 
[ERROR] ERROR in src/app/explore-data/explore-data/component/created-time-radio-filter.html(4,35): : Property '_startDateStr' is private and only accessible within class 'CreatedTimeRadioFilter'.
[ERROR] src/app/explore-data/explore-data/component/created-time-radio-filter.html(4,35): : Property '_endDateStr' is private and only accessible within class 'CreatedTimeRadioFilter'.
[ERROR] 
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! polaris2-ui@0.0.0 prod: `npm run package-reinstall && node --max_old_space_size=10240 ./node_modules/.bin/ng build --deploy-url /resource/ --output-hashing all --prod --base-href /app/v2/`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the polaris2-ui@0.0.0 prod script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by thinkcsww** [comment]
@ufoscw 
Modified build error

**Comment by ufoscw** [comment]
run build
deploy to 4

**Comment by ufoscw** [comment]
@thinkcsww 
please add "Updated time" Filter not "Created time"
> @thinkcsww
> Please add a Filter item. (Updated time)

**Comment by ufoscw** [comment]
@thinkcsww 

> @thinkcsww
> 
> 1. Layer does not close after selecting an option.
> 
> metatron_Discovery

I'll re-request this part after checking common UX. Please stay current.

**Comment by thinkcsww** [comment]
@ufoscw

Ok Thanks

**Comment by ufoscw** [comment]
@thinkcsww 
I don't mean to hold the whole thing. We need to modify the filter. (Created time -> Updated time)

**Comment by thinkcsww** [comment]
@ufoscw
Modified created time -> updated time

**Comment by ufoscw** [comment]
run build
deploy to 4

**Pull request merged**
