### PR TITLE
fix inital sort parameter in exploration data, fix re enter list view…

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

1. fix inital sort parameter in exploration data
2. fix re enter list view…
**Related Issue** : 

### How Has This Been Tested?

1. enter list view -> check sort parameter is not undefined in http request
2. Exploration data 
-> push enter in search bar , this will move to list view
-> come back to main view
-> push enter in search bar and check move to list view  is working

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 3

**Comment by ufoscw** [comment]
@thinkcsww 
1. Double clicking on a text input switches to list view.
metatron_Discovery

At this time, API is called twice.
DevTools_-_52_231_184_135_8187_app_v2_exploredata_view_page_0_size_20_sort_name_asc_type_ALL_및_fix_inital_sort_parameter_in_exploration_data__fix_re_enter_list_view…_by_thinkcsww_·_Pull_Request__2670_·_metatron-app_metatron-discovery


2. Double clicking on a text input requests rest api again.
The sort default is ascending, not descending.
Arrow direction is reversed.
metatron_Discovery

**Comment by thinkcsww** [comment]
@ufoscw 
Modified

**Comment by ufoscw** [comment]
run build
deploy to 3

**Pull request merged**
