### PR TITLE
#3266 Fix filter not working error

### PR DESCRIPTION
**Pull request by eltriny**
### Description

1. Data Filter Layer CSS error
2. Does not work after selecting Data Filter
3. Date filter check button CSS error

**Related Issue** : #3266 

### How Has This Been Tested?

1. Create a dashboard.
2. Add charts and filters.
3. Check if the option is displayed properly when the filter is selected on the browse screen.
4. Check if the filter is applied to the chart when the option is changed.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Pull request merged**
