### PR TITLE
F#1656 fix metadata guide message

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

Fix guide message in metadata detail and datasource detail

**Related Issue** : 

#1656 

### How Has This Been Tested?

1. Management -> Exploration ->  Metadata -> metadata detail
Check guide message in Information tab and column details tab

2. Management -> Datastorage -> Datasource -> datasource detail 
Check guide message in information tab 
Check guide message in column details -> column configure popup
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 2

**Comment by kyungtaak** [comment]
@ufoscw @thinkcsww check this the korean messages in below screen capture.
image
image

**Comment by thinkcsww** [comment]
@AnnieHwang 
What would be the proper translation?
image

**Comment by ufoscw** [comment]
@thinkcsww 
Please roll-back ko.json and Please translate "Data Lineage" into "데이터 리니지".

**Comment by thinkcsww** [comment]
@ufoscw 
Does it have to be a 'Data Lineage'?
image

**Comment by ufoscw** [comment]
@thinkcsww 
Sorry. 
en : Lineage
ko : 리니지

**Comment by thinkcsww** [comment]
@ufoscw 
Modified

**Comment by ufoscw** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Pull request merged**
