### PR TITLE
fix exploration data filter error

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

fix filter error 
show only one filter layer at once
fix filter is set to todayy when click between option
**Related Issue** : 

### How Has This Been Tested?

1. Exploration data -> list ivew 
2. check filter works properly

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 1

**Comment by ufoscw** [comment]
@thinkcsww 
When a category is clicked, the API is called twice, and the resulting grid shows the entire list rather than the category filtered list.

metatron_Discovery

DevTools_-_52_231_184_135_8185_app_v2_index_html

**Comment by thinkcsww** [comment]
@ufoscw 
when i click undefined show all list but when i click folder this is the result
image

**Comment by ufoscw** [comment]
Please click category when exploration main page.

**Comment by thinkcsww** [comment]
@ufoscw 
Modified

**Comment by ufoscw** [comment]
run build
deploy to 1

**Comment by ufoscw** [comment]
@thinkcsww 
1. "No selection reversed" when "Unclassified" is selected.
Do not show Unclassified when "Unclassified" is selected. **(Selecting "Unclassified" differs from not selecting a catalog.)**
Date filter has different behavior and labels for "DataSource" and "Exploration".

metatron_Discovery


2. Parameter error when selecting "Unclassified" (catalogId must be blank)
```
ex ) /api/metadatas?page=0&size=20&type=ALL&catalogId&projection=forListView
```
DevTools_-_52_231_184_135_8185_app_v2_exploredata_view_page_0_size_20_type_ALL_catalogId_285ea4bb-21d8-46f6-b38c-3e58ef8f8814

**Comment by thinkcsww** [comment]
@ufoscw 
Can you explain more detail about the meaning of no selection reversed when  'unclassified' is selected? 

Is that mean hide unclassified in lnb when select unclassified?

**Comment by ufoscw** [comment]
@thinkcsww 
When selecting "Unclassfied", the bold and underline styles should be applied.

**Comment by ufoscw** [comment]
run build
deploy to 1

**Comment by ufoscw** [comment]
run build
deploy to 1

**Pull request merged**
