### PR TITLE
fix searching task list in engine monitoring

### PR DESCRIPTION
**Pull request by minhyun2**
### Description

fix searching task list

**Related Issue** : 

### How Has This Been Tested?

1. Go to Engine monitoring.
2. Go to the task tab of the ingestion menu.
3. Check whether the search is normal and the page navigation works.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Review by ufoscw — APPROVED** [review]

**Pull request merged**
