### PR TITLE
#3263 separate chart edit view

### PR DESCRIPTION
**Pull request by eltriny**
### Description

Since the chart editing screen is dependent on the dashboard editing screen, there is no way to modify only the chart.

**Related Issue** : #3263 

### How Has This Been Tested?

1. Log in to discovery.
2. Check the ID of the page widget in the dashboard inquiry information.
3. Connect to the following address using the ID of the page widget.
     modify chart : /app/v2/edit-page?pageId=[pageWidgetId]
     new chart : /app/v2/edit-page?dashboardId=[dashboardId]
4. Check if it works normally.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Pull request merged**
