### PR TITLE
Temporarily modify the list of workspaces

### PR DESCRIPTION
**Pull request by eltriny**
### Description
The problem is that only the workbench appears in the list of workspaces.

**Related Issue** : 

### How Has This Been Tested?
The problem is that only the workbench appears in the list of workspaces.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by alchan-lee** [comment]
run build
deploy to 1

**Comment by minhyun2** [comment]
metatron_Discovery

@eltriny Please check the screenshot.

**Comment by alchan-lee** [comment]
run build
deploy to 1

**Comment by alchan-lee** [comment]
run build
deploy to 1

**Pull request merged**
