### PR TITLE
#3739 single date picker timefilter

### PR DESCRIPTION
**Pull request by eltriny**
### Description
If you set granularity , you need a filter that can select a single date.

**Related Issue** : #3739 

### How Has This Been Tested?

1. Open the filter creation popup.
2. Select the time field, select granularity, and make sure that there is a single time type in Filter Type.
3. After selecting a single time type, check if it is displayed normally on the panel.
4. Register the filter widget and check if it is displayed normally in the widget.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 1

**Review by minhyun2 — APPROVED** [review]

**Comment by minhyun2** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Review by ufoscw — APPROVED** [review]

**Review by minhyun2 — APPROVED** [review]

**Pull request merged**
