### PR TITLE
Fn fix exploration chart metadata css error

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

1. metadata detail tag align
2. fix datasource title ellipsis in chart screen
3. fix explore data main title css
4. In the data preview on the dashboard, the total value of the time filter does not display properly.
5. fix explore data main scroll error
**Related Issue** : 

### How Has This Been Tested?

1. management -> explore -> metadata -> click metadata -> check tags alignment is proper
2. go to workbook -> click datasource list dropdown button -> check title ellipsis works well
3. Exploration -> data -> check title shows properly
4. Preview data in the dashboard-> click the entire date range button-> check if the date is displayed normally
5. Exploration -> data -> check scroll works properly
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Comment by ufoscw** [comment]
@thinkcsww 
1. metadata detail "Catalog" is misaligned still. 
스크린샷_2019__11__14__오후_2_50

**Comment by thinkcsww** [comment]
@ufoscw 
Modified

**Comment by ufoscw** [comment]
deploy to 1

**Comment by ufoscw** [comment]
@thinkcsww 
metatron_Discovery

**Comment by minhyun2** [comment]
Please check the data grid tab in metadata management.
metatron_Discovery

**Comment by thinkcsww** [comment]
@ufoscw 
Modified

**Comment by kyungtaak** [comment]
deploy to 1

**Pull request merged**
