### PR TITLE
#2242 metadata col dictionary timestamp validation

### PR DESCRIPTION
**Pull request by paigechoi**
### Description

테스트 목록 기획서 참고해주세요.
image

1. Can't modify column dictionary when column is geo type
2. When removing Dictionary, initialise logical name, type, code table, description
3. Description is always editable whether you add a column dictionary or not
4. If you add a timestamp type column dictionary, you can modify the format
5. If metadata type is datasource and column role is timestamp,
type and format should not be changed when adding a column dictionary. It stays as timestamp

**Related Issue** : 

#2242 

### How Has This Been Tested?

Ran locally

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 6

**Comment by ufoscw** [comment]
@paigechoi 
5. If you remove a dictionary after applying a dictionary to a column of type timestamp, the timestamp type is not retained and is initialized to string.

**Comment by paigechoi** [comment]
@ufoscw Role이 timestamp일 경우 .. dictionary를 제거했을 때 type이 string으로 초기화되지 않게 수정했습니다..

**Comment by ufoscw** [comment]
run build
deploy to 6

**Comment by ufoscw** [comment]
@paigechoi 
Linked DataSource로 만들어진 Metadata일 경우 column schema 탭 진입할때 에러 Alert이 뜹니다.
http://52.231.153.96:8190/app/v2/management/metadata/metadata/15804414-e38b-4941-b21c-469ddd52fd5e

**Comment by paigechoi** [comment]
@ufoscw  /api/metadatas/${medatadId}?projection=forDetailView
image

linked 경우 커넥션 정보가 없습니다. source > source> injestion 안에 connection 정보를 넣어주시거나..
source > source 안에 connection 정보를 넣어주시면 감사하겠습니다. 

`/connections/query/data?extractColumnName=false&limit=100` API 를 사용하기 위해서 connection 정보가 필요합니다.......

**Comment by ufoscw** [comment]
run build
deploy to 6

**Comment by kyungtaak** [comment]
@ufoscw @paigechoi I think the code table in geo column is also meaningless.
image

**Pull request merged**
