### PR TITLE
fn-fix_code_table_error

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

2992
if anything is modified in codetable enable reset button and save button otherwise disable
save data without confirm modal

2990
fix delete icon overlap modified date

**Related Issue** : 

METATRON-2992
METATRON-2990

### How Has This Been Tested?

2992
1.Management -> explore data -> code table -> click item
2. change code table data and check buttons are working properly

2990
1. Management -> explore data -> code table 
2. check delete icon is overlap the list when hover above list
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
@thinkcsww 
please check compile error
```
[ERROR] 
[ERROR] ERROR in src/app/meta-data-management/code-table/detail-code-table/detail-code-table.component.html(230,16): : Property 'isCodeListModified' is private and only accessible within class 'DetailCodeTableComponent'.
[ERROR] src/app/meta-data-management/code-table/detail-code-table/detail-code-table.component.html(237,16): : Property 'isCodeListModified' is private and only accessible within class 'DetailCodeTableComponent'.
[ERROR] 
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! polaris2-ui@0.0.0 prod: `npm run package-reinstall && node --max_old_space_size=10240 ./node_modules/.bin/ng build --deploy-url /resource/ --output-hashing all --prod --base-href /app/v2/`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the polaris2-ui@0.0.0 prod script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
```

**Comment by thinkcsww** [comment]
@ufoscw 
수정했습니다.

**Comment by ufoscw** [comment]
run build
deploy to 1

**Comment by ufoscw** [comment]
@thinkcsww 
Console error when entering Code in Code table
DevTools_-_52_231_184_135_8185_app_v2_management_metadata_code-table_및_metatron_Discovery

**Comment by thinkcsww** [comment]
@ufoscw 
수정했습니다.

**Comment by ufoscw** [comment]
@thinkcsww 
please check code conflicts.

**Comment by thinkcsww** [comment]
@ufoscw 
수정했습니다.

**Comment by ufoscw** [comment]
run build
deploy to 1

**Comment by kyungtaak** [comment]
@thinkcsww The button works even though it is disabled.
image

**Comment by thinkcsww** [comment]
@kyungtaak 
Corrected.

**Comment by thinkcsww** [comment]
@kyungtaak 
Modified

**Comment by kyungtaak** [comment]
run build
deploy to 1

**Comment by kyungtaak** [comment]
run build
deploy to 1

**Comment by kyungtaak** [comment]
@thinkcsww you need to adjust icon location (and I hope.. check column dictionary list view as well)
image

**Comment by thinkcsww** [comment]
@kyungtaak 
Modified

**Comment by kyungtaak** [comment]
run build
deploy to 1

**Pull request merged**
