### PR TITLE
#1504 Icon overlaps the last column of query result

### PR DESCRIPTION
**Pull request by eltriny**
### Description

워크벤치 쿼리 결과에서 마지막 row 의 마지막 column 값이 확인 불가함

**Related Issue** : #1504 

### How Has This Been Tested?

1. 워크벤치에서 쿼리 실행합니다.
2. 쿼리 결과가 표시된 후 스크롤을 제일 아래로 내렸을 떄 아이콘 이미지가 숨겨지는지 ( 흐릿하게 ) 확인합니다.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by kyungtaak** [comment]
@metatron-app/design @AnnieHwang plz review this pr

**Comment by kyungtaak** [comment]
@eltriny I do not know if the build is working properly. But I think the modified function does not work.
image

**Comment by eltriny** [comment]
@kyungtaak 수정했습니다.

**Comment by kyungtaak** [comment]
run build
deploy to 2

**Comment by kyungtaak** [comment]
run build
deploy to 2

**Pull request merged**
