### PR TITLE
#1331 column rename for hive snapshot

### PR DESCRIPTION
**Pull request by paigechoi**
### Description

Automatically generates names that are appropriate for creating a hive snapshot

**Related Issue** : 

#1331 

### How Has This Been Tested?

Check #1331 for test details.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by joohokim1** [comment]
run build
deploy to 5

**Comment by joohokim1** [comment]
run build
deploy to 5

**Comment by joohokim1** [comment]
run build
deploy to 5

**Comment by minjung-cho** [comment]
@joohokim1 @paigechoi 
테스트 리뷰입니다
1. 오토 네이밍 시, 이름 중복 체크도 되어야 합니다.
스크린샷 2019-03-22 오전 7
팝업에서는 '중복 이름' 문구가 표시되지 않지만
스크린샷 2019-03-22 오전 7 22 52
룰 편집 그리드의 컬럼명을 보면 그냥 바뀌어 있습니다.
2. 화면 캡처하면서 발견한 현상입니다. 큰 문제는 아닙니다만, 한번 확인 부탁드립니다.
2.1. 중복 이름 입력 -> '중복이름' 문구 보임
스크린샷 2019-03-22 오전 7 28 03
2.2. Command 키(Mac OS) 누름
2.3. '중복이름' 문구 사라짐
스크린샷 2019-03-22 오전 7 28 16

**Comment by teamsprint** [comment]
run build
deploy to 5

**Comment by teamsprint** [comment]
run build
deploy to 5

**Comment by joohokim1** [comment]
run build
deploy to 5

**Comment by joohokim1** [comment]
run build
deploy to 5

**Comment by paigechoi** [comment]
@joohokim1  Found bug .. closing this issue for now sorry!

**Comment by joohokim1** [comment]
run build
deploy to 5

**Comment by joohokim1** [comment]
run build
deploy to 5

**Comment by joohokim1** [comment]
run build
deploy to 5

**Pull request merged**
