### PR TITLE
fn fix checkbox in notebook list

### PR DESCRIPTION
**Pull request by sting009**
### Description

노트북 서버 목록 화면에서 체크박스 전체 선택 후 타입변경시 체크박스가 풀리는 내용을 수정합니다. 

**Related Issue** : 통합테스트 

### How Has This Been Tested?

1. notebook server 목록 화면으로 이동합니다. 
2. 전체 체크박스 선택을 클릭합니다. 
3. 타입을 변경 시, 선택된 체크박스가 유지되는지 확인합니다. 

#### Need additional checks?
체크박스 선택 해제 이벤트가 문제가없는지 확인합니다. 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 6

**Comment by ufoscw** [comment]
@sting009 
'ALL' checkbox is checked if the list is empty at the first screen entry.
metatron_Discovery

**Comment by ufoscw** [comment]
run build
deploy to 6

**Comment by sting009** [comment]
@ufoscw 
image

Fixed an error the 'ALL' checkbox was selected when the list was empty.

**Comment by ufoscw** [comment]
run build
deploy to 3

**Comment by ufoscw** [comment]
@sting009 
When changing Type, unnecessary lower "More" button will appear and disappear.

**Pull request merged**
