### PR TITLE
F#795 horizontal scroll in histogram area

### PR DESCRIPTION
**Pull request by imsaaks**
### Description

add function horizontal scroll in histogram area
(This function does not work in the ie browser.)

**Related Issue** : 

#795 

### How Has This Been Tested?

1. menu MANAGEMENT > DataPreparation > Dataflow
2. click dataflow item
3. click Wrangled item > click Edit rules button
4. test using the touchpad. [Horizontal scroll in histogram area] 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by imsaaks** [comment]
This function does not work in the ie browser.

**Comment by joohokim1** [comment]
run build
deploy to 6

**Comment by joohokim1** [comment]
@imsaaks 
Then what does happen in IE if we accept this change?
1. On histogram area
2. Out of histogram area

**Comment by sang-hee-lee** [comment]
Added horizontal scrolling in header area.I'd like to request a rebuild.

**Pull request merged**
