### PR TITLE
F#2699 change filter in exploration list and fix bug

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

2606 - Change exploration data main 
2699 - change explore data list filter and fix bug 
**Related Issue** : 

#2606 
#2699 

### How Has This Been Tested?

1. Explore data main - Check new design is applied and carousel is working well.
2. Explore data list filter - check filter is working well

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
@thinkcsww 
The search must be done without specifying a "to" or "from" time in the between date filter.
metatron_Discovery

Please request the parameters as shown below.

1. {date} ~ current time
```
(GET) /api/metadatas?searchDateBy=UPDATED&from={date}
```

2. Past time ~ {date}
```
(GET) /api/metadatas?searchDateBy=UPDATED&to={date}
```

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
@thinkcsww 
1. Change sorting condition > Refresh screen > Enter list screen > Screen and parameter do not match
metatron_Discovery_및_DevTools_-_52_231_184_135_8186_app_v2_exploredata_view_page_0_size_20_sort_modifiedTime_asc_type_ALL_catalogId_

2. Set the date filter to "2019-10-01 17:56 ~ Current time" > Refresh screen > Enter list screen > The parameter will be displayed as "invalid date".
DevTools_-_52_231_184_135_8186_app_v2_exploredata_view_page_0_size_20_sort_modifiedTime_asc_searchDateBy_UPDATED_from_2019-10-01T17_56_00_000_2B09_00_catalogId_

**Comment by thinkcsww** [comment]
@ufoscsw
Modified

**Comment by ufoscw** [comment]
run build
deploy to 1

**Pull request merged**
