### PR TITLE
Dashboard router fragment function was added.

### PR DESCRIPTION
**Pull request by eltriny**
### Description

Display url when entering the Dashboard screen

**Related Issue** : #3643  

### How Has This Been Tested?

스크린샷 2021-04-05 오후 4 13 58
1. Check if the dashboard URL is copied when clicking the dashboard icon.
2. When entering the copied URL, check whether it moves without initial loading.
3. Check if the dashboard is displayed as the address changes when clicking on the dashboard list.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Review by ufoscw — APPROVED** [review]

**Review by minhyun2 — APPROVED** [review]

**Pull request merged**
