### PR TITLE
#3638 bump type script angular

### PR DESCRIPTION
**Pull request by eltriny**
### Description

Bump TypeScript, Angular
Target version needs to be confirmed..

**Related Issue** : #3638 

#### Need additional checks?
Overall function check

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Review by ufoscw — APPROVED** [review]

**Review by minhyun2 — DISMISSED** [review]

**Comment by minhyun2** [comment]
deploy to 2

**Review by ufoscw — APPROVED** [review]

**Review by minhyun2 — APPROVED** [review]

**Pull request merged**
