### PR TITLE
Fn fix exploredata error

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

1. An error occurs when [Management] Metadata Details> Go to Data Source> Delete Data Source.
2. [Management] Data search> Searchability on / off does not work when generating metadata.
3. In the [Management] Data Navigation> Code Table> Search Result List screen, the delete icon UI overlaps.
4. The [Management] metadata table list is different from the plan.
5. In the [Management] Data Navigation> Glossary> Glossary Registration popup, after entering the glossary name, the validity check is not performed properly when focusing out.
6. Fix when click some data can't go to detail view in explore data
7. fix resize component when lnb is folded in explore data

**Related Issue** : 

METATRON-3020
METATRON-3003
METATRON-2990
METATRON-2955
METATRON-2989
METATRON-2971
METATRON-3023
#2501 

### How Has This Been Tested?

2971
1. Explore Data 
image
Check especially  when click data right above, detail pop up is showing 

3023
1. Explore Data
Check The main banner's text and tag ellipsis is working

2501
1. Explore data
check when fold lnb explore component is resize correctly

1. Go to [Management] Metadata Details> Data Sources> Verify that the data source is deleted correctly.
2. Check if [Management] data exploration> metadata creation is turned off or disabled.
3. On the [Management] Data Navigation> Code Table> Search Result List screen, confirm that the Delete icon UI is displayed correctly.
4. Confirm that the [Management] metadata table list form is displayed as planned.
5. In the [Management] Data Navigation> Glossary> Glossary Registration popup, enter the glossary name and check if the validity check works properly when focusing out.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 5

**Comment by ufoscw** [comment]
@thinkcsww 
ellipsis is not working at main banner and side banner
metatron_Discovery

**Comment by kyungtaak** [comment]
run build
deploy to 3

**Comment by kyungtaak** [comment]
run build
deploy to 3

**Comment by ufoscw** [comment]
run build
deploy to 5

**Comment by ufoscw** [comment]
@thinkcsww 
1. Management > Metadata > Detail
 : Delete catalog button is missing
 : Validation check required when assigning duplicate catalog
metatron_Discovery

2. Explore Data
 : Side banner disappears when text is longer
metatron_Discovery_및_DevTools_-_discovery_metatron_app_app_v2_workspace_및_DevTools_-_localhost_8180_app_v2_workspace

**Comment by thinkcsww** [comment]
@ufoscw 
I can reproduce in other branches, but i can't reproduce in fn-fix_exploredata_error branch

If tag overflow the container display like below and if text is overflow ellipsis is showing..

image

**Comment by ufoscw** [comment]
@thinkcsww 
Sorry. I think there was a problem when testing.
There was no problem with the recommend banner.
metatron_Discovery

**Comment by thinkcsww** [comment]
@ufoscw 
Modified

**Comment by ufoscw** [comment]
run build
deploy to 5

**Comment by ufoscw** [comment]
@thinkcsww 
Modify the delete button to expose it on mouse over as shown in wireframe.
And the description "undefined" error fix seems to have been reverted.

**Comment by thinkcsww** [comment]
@ufoscw 
fixed version of undefine error is in 'fn-fix_mdm_metadata_edit_error branch'

Do you want me to merge that branch into this branch?

**Comment by ufoscw** [comment]
@thinkcsww 
The "fn-fix_mdm_metadata_edit_error" branch has been merged into the master and should be included when reflected in the testbed.
No additional branch merge is necessary.
I will check again after reflecting master.

**Comment by thinkcsww** [comment]
@ufoscw 

Ok and publishing task is in progress

**Comment by thinkcsww** [comment]
@ufoscw 
Modified

**Comment by ufoscw** [comment]
run build
deploy to 5

**Pull request merged**
