### PR TITLE
#2120 measure data can be replaced with a negative value

### PR DESCRIPTION
**Pull request by minhyun2**
### Description
the measure data can be replaced with a negative value in the data source ingestion process.

**Related Issue** : #2120 

### How Has This Been Tested?

1. Go to datasource.
2. Create new datasource.
3. In the schema configuration step, enter a negative value in the replace value.
image

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
run build
deploy to 4

**Comment by kyungtaak** [comment]
@minhyun2 @AnnieHwang 
1. If I change the data type, the "missing" option selection is not retained.
2. It seems that the focus-out event should also be checked.

**Comment by minhyun2** [comment]
run build
deploy to 4

**Comment by minhyun2** [comment]
run build
deploy to 4

**Comment by minhyun2** [comment]
run build
deploy to 4

**Comment by minhyun2** [comment]
run build
deploy to 4

**Comment by kyungtaak** [comment]
run build
deploy to 4

**Comment by kyungtaak** [comment]
run build
deploy to 4

**Comment by kyungtaak** [comment]
@minhyun2 I'll test for replace function with updated cube engine

**Pull request merged**
