### PR TITLE
#1882 About Liner Predictive

### PR DESCRIPTION
**Pull request by eltriny**
### Description

스크립트 오류가 발생하면서 예측선이 그려지지 않습니다.

**Related Issue** : #1882 

### How Has This Been Tested?

1. timestamp 를 차원값으로 하여 라인차트를 생성합니다.
2. 예측선 표시를 On 으로 변경합니다.
3. 정상적으로 예측선이 표시되는지 확인합니다.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kyungtaak** [comment]
run build
deploy to 3

**Comment by alchan-lee** [comment]
run build
deploy to 3

**Comment by kyungtaak** [comment]
@eltriny Check below screenshot!
image

**Comment by eltriny** [comment]
@kyungtaak 수정했습니다.

**Comment by ufoscw** [comment]
run build
deploy to 3

**Pull request merged**
