### PR TITLE
#2178 enhance re-ingestion datasource with file

### PR DESCRIPTION
**Pull request by minhyun2**
### Description

Enhance re-ingestion datasource with file

**Related Issue** : #2178 

### How Has This Been Tested?

1. Go to datasource whose Source type is My File.
2. Click Re-Ingestion.
3. Upload new file.
4. If the schema is the same or add new column, it will be appended.
5. If the schema is different, it will be overwritted.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by AnnieHwang** [comment]
@kyungtaak @minhyun2 인제스쳔 중간에도 Re-ingestion 버튼이 활성화 되서 눌러봤는데.. 정상적으로 잘 동작하긴 하더라고요.  Re-ingestion버튼을 활성화 해 둬도 괜찮겠죠?
image

**Comment by kyungtaak** [comment]
> 인제스쳔 중간에도 Re-ingestion 버튼이 활성화 되서 눌러봤는데.. 정상적으로 잘 동작하긴 하더라고요. Re-ingestion버튼을 활성화 해 둬도 괜찮겠죠?

@AnnieHwang 흠.. 그럼 안될것 같네요.
@minhyun2 혹시 퀵하게 수정가능한가요?

**Comment by minhyun2** [comment]
@AnnieHwang @kyungtaak status가 ENABLED 일 경우에만 버튼이 보이도록 수정하겠습니다.

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by kyungtaak** [comment]
run build
deploy to 2

**Pull request merged**
