### PR TITLE
F#1350 download file of imported dataset

### PR DESCRIPTION
**Pull request by sang-hee-lee**
### Description

Download file of imported dataset(only Upload Uri type)

**Related Issue** : 

#1350 

### How Has This Been Tested?

1. menu> Data Preparation > Dataset
2. Click Imported dataset(upload, file type)
3. Click URI and check download

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by joohokim1** [comment]
run build
deploy to 5

**Comment by ksparknot** [comment]
run build
deploy to 5

**Comment by ksparknot** [comment]
run build
deploy to 5

**Comment by ksparknot** [comment]
run build
deploy to 5

**Comment by ksparknot** [comment]
run build
deploy to 2

**Pull request merged**
