### PR TITLE
F#2603 metadata detail add dashboard thumbnail

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

add dashboard thumbnail in metadata detail modal
**Related Issue** : 

#2603 

### How Has This Been Tested?

1. Exploration -> data
2. click datasource card
3. check dashboard thumbnail is showing properly
4. check when click dashboard showing dashboard in new window
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 1

**Comment by ufoscw** [comment]
@thinkcsww 
Please do the unit test and open PR.
metatron_Discovery

**Comment by thinkcsww** [comment]
@ufoscw
sorry for that

**Comment by ufoscw** [comment]
run build
deploy to 5

**Comment by thinkcsww** [comment]
@ufoscw 
Modified
image

**Comment by ufoscw** [comment]
@thinkcsww 
1. ellipsis does not work with builds merged with master.
metatron_Discovery

2. An error occurs when there is no recently used dashboard
DevTools_-_52_231_153_96_8189_app_v2_exploredata_view

**Comment by thinkcsww** [comment]
@ufoscw 
Modified
I merged master into this branch and test. 

image

image

**Comment by ufoscw** [comment]
run build
deploy to 5

**Comment by ufoscw** [comment]
@thinkcsww 
1. The hand cursor area is incorrectly allocated.
Only areas that can be clicked into the dashboard should be assigned to the hand cursor.
metatron_Discovery

2. There is no ellipsis if no link permission.
metatron_Discovery

**Comment by ufoscw** [comment]
run build
deploy to 6

**Comment by ufoscw** [comment]
@thinkcsww 
metatron_Discovery

**Comment by thinkcsww** [comment]
@ufoscw 
Modified

**Comment by ufoscw** [comment]
run build
deploy to 6

**Pull request merged**
