### PR TITLE
#101 modify node model for duplicated field name

### PR DESCRIPTION
**Pull request by juheeko9**
### Description

- source와 target의 데이터값이 같은경우 양방향으로 설정
- source와 target의 데이터값이 같은 노드에 호버시 툴팁이 source / target을 두개다 표시

**Related Issue** : #101 

### How Has This Been Tested?
- source와 target에서 데이터값이 같은경우 양방향으로 표시되는지 확인
- source와 target에서 데이터값이 같은경우 툴팁에서 source, target에 대한 데이터정보가 표시되는지 확인

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by kyungtaak** [comment]
run build
deploy to 4

**Comment by juheeko9** [comment]
@kyungtaak PR에 올렸던 내용이 정상적으로 반영되지 않았습니다.
로컬에서는 mergeNode 파라미터값이 정상적으로 설정되어 nodes값에서 fields값으로 리턴되는것을 확인하였으나
테스트서버 4에서는 설정된 파라미터값이 반영되지 않은것으로 확인하였습니다. 
확인부탁드립니다.

[로컬에서 확인시]
screen shot 2018-09-18 at 2 04 41 pm
screen shot 2018-09-18 at 2 04 48 pm

**Comment by kyungtaak** [comment]
@eltriny 5번으로 빌드를 다시해보겠습니다.

**Comment by kyungtaak** [comment]
run build
deploy to 5

**Comment by juheeko9** [comment]
@kyungtaak 
5번 테스트서버에서 mergeNode: true, useLinkCount: true로 설정하여 조회해보았으나
nodes의 값이 fields로 리턴되는것이 아닌 field로 리턴됩니다. 
해당 브랜치에서 적용된 내용이 반영되지 않고있는 것 같습니다. 

[API]
POST http://52.231.184.181:8189/api/datasources/query/search

[Request Body]
`{"context":{"discovery.route.uri":"/workbook/46b9b342-e4ef-4633-89f6-f9620e55f9ac","discovery.dashboard.id":"b55d6e87-74a3-49a4-bd95-370c137f12ed"},"dataSource":{"joins":[],"temporary":false,"id":"ds-37","name":"sales","uiDescription":"sales data (2011~2014)","type":"default","connType":"ENGINE","engineName":"sales"},"filters":[{"field":"OrderDate","dataSource":"sales","type":"time_all"}],"pivot":{"columns":[{"type":"dimension","name":"Category","subType":"STRING","subRole":"DIMENSION","alias":"Category"}],"rows":[{"type":"dimension","name":"Region","subType":"STRING","subRole":"DIMENSION","alias":"Region"}],"aggregations":[{"type":"measure","aggregationType":"SUM","name":"Discount","subType":"DOUBLE","subRole":"MEASURE","format":{"type":"number","sign":"KRW","decimal":2,"useThousandsSep":true,"abbr":"NONE","customSymbol":null},"alias":"SUM(Discount)"}]},"limits":{"limit":100000,"sort":[]},"aliases":[{"type":"value","ref":"b55d6e87-74a3-49a4-bd95-370c137f12ed"}],"resultFormat":{"type":"graph","useLinkCount":true, "mergeNode": true}}`

[Return]
`{"nodes":[{"field":"Region","name":"Central","value":558.3400110155344},{"field":"Region","name":"East","value":414.00000247359276},{"field":"Region","name":"South","value":238.55000030994415},{"field":"Region","name":"West","value":350.2000030428171},{"field":"Category","name":"Furniture","value":368.89000813663006},{"field":"Category","name":"Office Supplies","value":947.8000056296587},{"field":"Category","name":"Technology","value":244.40000307559967}],"links":[{"sourceField":"Category","source":"Furniture","targetField":"Region","target":"Central","value":481},{"sourceField":"Category","source":"Furniture","targetField":"Region","target":"East","value":600},{"sourceField":"Category","source":"Furniture","targetField":"Region","target":"South","value":332},{"sourceField":"Category","source":"Furniture","targetField":"Region","target":"West","value":707},{"sourceField":"Category","source":"Office Supplies","targetField":"Region","target":"Central","value":1422},{"sourceField":"Category","source":"Office Supplies","targetField":"Region","target":"East","value":1712},{"sourceField":"Category","source":"Office Supplies","targetField":"Region","target":"South","value":995},{"sourceField":"Category","source":"Office Supplies","targetField":"Region","target":"West","value":1897},{"sourceField":"Category","source":"Technology","targetField":"Region","target":"Central","value":420},{"sourceField":"Category","source":"Technology","targetField":"Region","target":"East","value":535},{"sourceField":"Category","source":"Technology","targetField":"Region","target":"South","value":293},{"sourceField":"Category","source":"Technology","targetField":"Region","target":"West","value":599}]}`

[참고화면]
screen shot 2018-09-18 at 6 15 11 pm

**Comment by kyungtaak** [comment]
@juheeko9 해당 브렌치는 제가 커밋한 내용만 있는데요. 다시한번 확인부탁드립니다.

**Pull request closed without merging**
