### PR TITLE
fn-fix_ie_ui_error

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

3023 
fix explore data detail description overflow

3030
fix workbench, workbook title and description overlap

3031
fix exploredata recommend data ui overlap

3033 
fix metadata detail - title description overflow 

3034
fix data flow description overflow

3036 
fix data description overflow
**Related Issue** : 

METATRON3023
METATRON3030
METATRON3031
METATRON3033
METATRON3034
METATRON3036

### How Has This Been Tested?

3023 
1. explore data -> click data card which has long description
2. check description shows properly

3030
1. workspace -> workbench & workbook which has long description and title
2.  check description and title show properly

3031
1. exploredata 
2. check recommend banner ui shows properly

3033
1.Management -> explore data -> metadata
2. click metadata which has long title
3. check title and description shows properly

3034
1. Management -> Data flow -> data
2. check description shows properly

3036
1. Administartion -> workspace -> workspace 
2. click data which has long text
3. check ellipsis is working properly
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 4

**Comment by ufoscw** [comment]
@thinkcsww 
There is no ellipsis tooltip.
1. Management > Metadata > Detail
Windows_7

2. Explore Data > Detail
Windows_7

3. Workspace > workbook, workbench
Windows_7

4. Workbook
Windows_7

5. Workbench
Windows_7

**Comment by thinkcsww** [comment]
@ufoscw
Modified

**Comment by ufoscw** [comment]
run build
deploy to 4

**Comment by ufoscw** [comment]
@thinkcsww 
Ellipsis disappears in workspace.
metatron_Discovery

**Comment by thinkcsww** [comment]
@ufoscw 
Modified

**Comment by ufoscw** [comment]
run build
deploy to 4

**Pull request merged**
