### PR TITLE
F#1493 use json for map array

### PR DESCRIPTION
**Pull request by joohokim1**
### Description
I've changed the internal structure Array and Map types from Java Objects to JSON strings.
Now, we can create an Array or Map (Object in a common word) types from String type values.

**Related Issue** : #1493 

### How Has This Been Tested?
1. Import & wrangle [json_in_column.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3823084/json_in_column.csv.txt)
2. Click column1's context menu - Alter - Column type - Map
3. Click column1's context menu - Generate - Unnest
4. Click "Add" without any argument.
5. You'll see "A", "B_1" columns generated. (B_1 is because of name duplication)

스크린샷 2019-11-08 오후 2 25 47

#### Need additional checks?
Yes, please.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by joohokim1** [comment]
deploy to 6

**Comment by alchan-lee** [comment]
@joohokim1 
Is it not support to use this in the nested json?
I've tested with [this file](https://github.com/metatron-app/metatron-discovery/files/3823191/jsonjson.csv.txt) but it fails when nested. 😢 



image

**Comment by joohokim1** [comment]
@alchan-lee @ksparknot Because we had to test a non-quoted (or weird-quoted) file, I've configured dataprep.polaris.quoteChar as null. Currently, even the test scenario I wrote above does not work. Sorry for your time. #2835 will solve the quote problem.

**Comment by joohokim1** [comment]
deploy to 6

**Comment by joohokim1** [comment]
deploy to 6

**Comment by joohokim1** [comment]
@ksparknot @kyungtaak @alchan-lee 
I've merged https://github.com/metatron-app/metatron-discovery/pull/2836 onto this PR branch.
You can set the quote character like this:
스크린샷 2019-11-11 오전 12 10 03

This PR is ready to merge. I'll be appreciate if you could re-check and approve.

**Comment by kyungtaak** [comment]
@joohokim1 thanks for your effort and support :)

**Pull request merged**
