### PR TITLE
#2491 index of selected node will be clear when reloading linege view

### PR DESCRIPTION
**Pull request by ksparknot**
### Description
1. index of selected node will be clear when reloading linege view
2. test file has txt extension. now txt is supported
3. test file has not a tier field. it is not a right format. now this will make an error.

**Related Issue** :
[#2491](https://github.com/metatron-app/metatron-discovery/issues/2491)

### How Has This Been Tested?
1. decrease the node count. 
2. click all nodes.

If all nodes are selected. that is ok

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ksparknot** [comment]
run build
deploy to 1

**Comment by ksparknot** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
@ksparknot 
We have to refix below:
- When drag & drop other than .csv, .txt (like .json) no error message pops out and nothing happens.

Things done:
- When the node count changed, we can click icons now.
- When a mandatory column is missing, the user gets an error message to fix it.
- .txt files are now permitted. After this PR, only .csv we accepted only .csv files.

Because of QA release. We'll merge this PR.
A PR for refix should be made ASAP.

**Pull request merged**
