### PR TITLE
#2961 improve query detail and datasource list in engine monitoring

### PR DESCRIPTION
**Pull request by minhyun2**
### Description

Improve query detail and datasource list in engine monitoring

**Related Issue** : #2961 

### How Has This Been Tested?

1. Go to Engine Monitoring
2. Go to Query tab and check Query detail UI change.
3. Go to datasource tab and check the enable / disable / permanently delete function.
  a Change the data source that is in the enable status to disable.
  b Verify that it is changed to disable in the datasource list. (It may take a few minutes.)
  c Enable the disabled data source and confirm the status change.
  d Permanently delete the data source and make sure it is not visible in the data source list.
  e Using Retention, drop a specific interval or period.
  f Enable to check if the entire data is available.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 5

**Comment by alchan-lee** [comment]
deploy to 5

**Comment by alchan-lee** [comment]
deploy to 5

**Comment by alchan-lee** [comment]
deploy to 5

**Comment by alchan-lee** [comment]
deploy to 5

**Comment by minhyun2** [comment]
deploy to 5

**Comment by minhyun2** [comment]
deploy to 5

**Comment by minhyun2** [comment]
deploy to 5

**Comment by kyungtaak** [comment]
@minhyun2 sort function is too slow to view the query list. Is there any solution?

**Comment by minhyun2** [comment]
deploy to 5

**Pull request merged**
