### PR TITLE
#3295 support responsive web of external login page

### PR DESCRIPTION
**Pull request by minhyun2**
### Description

Support external login page for responsive web

**Related Issue** : #32955

### How Has This Been Tested?

1. Register the oauth client. (can register the logo, favicon, background image, copyright html)
2. Login the the oauth client.
3. Check the login page at many resolutions.
4. Reset password and login the client. (Check the change password popup).
5. Login the oauth client and login the same oauth client at the different IP. (Check the notification popup)

- Over width 500px
metatron_Discovery

- Under width 500px
metatron_Discovery

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 1

**Comment by kyungtaak** [comment]
@minhyun2 I would like to add an explanation of how to call the login view from an external client. :)

**Comment by minhyun2** [comment]
> @minhyun2 I would like to add an explanation of how to call the login view from an external client. :)

In this PR([https://github.com/metatron-app/metatron-discovery/pull/3192](https://github.com/metatron-app/metatron-discovery/pull/3192)), there is a guide for registering external clients.

Also, below is a guide to edit.
URL : /api/oauth/test_client
RequestBody : example
{ "faviconPath": "/static/favicon.ico",
  "logoFilePath": "/static/logo.svg",
  "backgroundFilePath": "/static/background.jpg",
  "smallLogoDesc": "This is Test Client",
  "copyrightHtml": "<b>This is Test Client</b>
  <span>Copyright © metatron.app All rights reserved.</span>"
}
Header : Authorization (Bearer {})
Response Status : 204

and also, I already registered a test client.
{testbedDomain}/oauth/authorize?response_type=code&client_id=test_client&redirect_uri=https://metatron.app/&scope=read

**Comment by minhyun2** [comment]
deploy to 1

**Pull request merged**
