### PR TITLE
#2426 - add confirm modal when navigate

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

show confirm modal before navigate between metadata and datasource
**Related Issue** : 

#2426 

### How Has This Been Tested?

1.  management -> Exploration -> metadata -> metadata detail -> click go to datasource button
2. management -> data storage -> datasource -> datasource detail -> click go to metadata button 
3. Exploration -> data -> metadata detail modal -> click edit data
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 3

**Comment by ufoscw** [comment]
@thinkcsww 
You are using the same message in different code.
Please change to the same code.

Please use messages below.
```
"msg.storage.alert.metadata.column.code.table.detail.modal.name" :"Do you want to close this page and move?",
"msg.storage.alert.metadata.column.code.table.detail.modal.description" :"Click cancel, if you don't want move",
"msg.storage.alert.metadata.column.code.table.detail.modal.btn": "Close and move",
```

Please discard messages below.
```
"msg.explore.ui.confirm.title" : "Do you want to close and move the current screen?",
"msg.explore.ui.confirm.description" : "Select Cancel to not move.",
"msg.explore.btn.confirm.done" : "Close and move",
```

and The modal area does not cover the GNB.
metatron_Discovery

**Comment by thinkcsww** [comment]
@ufoscw 
Modified

**Comment by ufoscw** [comment]
deploy to 3

**Pull request merged**
