### PR TITLE
F#2298 generate metadata when datasource enabled

### PR DESCRIPTION
**Pull request by ufoscw**
### Description
Changes metadata creation time since creation of datasource

**Related Issue** : #2298 

### How Has This Been Tested?
1. create DataSource normally.
2. The "Go to Metadata" button should not be present immediately after creation.
3. The "Go to Metadata" button should appear after the completion message.

1. create DataSource again (for error)
2. To create a DataSource ingestion error, add the column using the wrong longitude, latitude column.
3. The "Go to Metadata" button should not be present immediately after creation.
4. DataSource should not appear in metadata list after error occurs.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 4

**Comment by ufoscw** [comment]
run build
deploy to 4

**Comment by kyungtaak** [comment]
@brandon-wonjune @ufoscw 
Even though ingestion success, the "Go to Metadata" button does not appear after ingestion in the detail view that appears after creating the data source.
_데이터 소스 생성 후 나타나는 상세화면 내에서 적재 작업이 끝난 후 "Go to Metadata" 버튼이 나오지 않습니다._ 
image

**Comment by ufoscw** [comment]
@kyungtaak 
Changed metadata generation time before topic sending.

**Comment by ufoscw** [comment]
run build
deploy to 4

**Pull request merged**
