### PR TITLE
#353 Error saving pie chart after setting color by measure

### PR DESCRIPTION
**Pull request by juheeko9**
### Description
- 파이차트를 color by measure로 저장 시 format 정보가 초기화 되어 저장에러가 발생합니다.

**Related Issue** : #353 

### How Has This Been Tested?
- 파이차트를 선택 후 색상패널에서 color by measure로 선택 후 저장시 저장에러가 발생하지 않는지 확인하였습니다.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alchan-lee** [comment]
run build
deploy to 5

**Comment by alchan-lee** [comment]
run build
deploy to 1

**Comment by kyungtaak** [comment]
@juheeko9 기능은 확인하였으나, 간단하게 추가 수정후 PR 리오픈 부탁드립니다.
image

**Comment by kyungtaak** [comment]
run build
deploy to 1

**Pull request merged**
