### PR TITLE
Fixed an error that occurred when using the `ifcountd` function in a user-defined field

### PR DESCRIPTION
**Pull request by kyungtaak**
### Description
Fixed an error that occurred when using the `ifcountd` function in a user-defined field.

**Related Issue** : None

### How Has This Been Tested?
1. Create a dashboard utilizing the Sales data source.
2. Create a user-defined column of measure type.
3. Create a expression using the `ifcountd` function, enter an arbitrary column name, and create a column. ex. `IFCOUNTD( [Region]  != 'East',  [Region] )` 
image
4. Create a chart using this column.
5. Confirm that the chart is displayed without errors.
image

#### Need additional checks?
- Check that no other aggregate functions are working.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by kyungtaak** [comment]
run build
deploy to 1

**Comment by alchan-lee** [comment]
@kyungtaak 
I think some results of ifcountd are not intended.

It should be calculated as;
(Total count) - (Count of matching an if statement) = (Count of not matching an if statement)

Am I misunderstanding this formula? 😮

image

**Comment by kyungtaak** [comment]
@alchan-lee :) The `ifcountd` function uses a cardinality aggregator in druid engine internally, unlike the `countd` function. As mentioned in the [link](https://druid.apache.org/docs/latest/querying/aggregations.html), this cardinality aggregator may be less accurate. This part requires work on the engine separately, which seems to be out of line with the current issue.

**Comment by dinhthengoc2021998** [comment]
Sorry, i have a stupid questions. In the created chart screen, when i apply Year( [action_date] ) function on a timestamp field [action_date], i obtain just only one value (-1). 
This function is OK when i apply this function on a single timestamp value. Can u help me.
image

**Pull request merged**
