### PR TITLE
#1820 Workbench icon reordered for extended connections

### PR DESCRIPTION
**Pull request by eltriny**
### Description
Workbench icon reordered for extended connections.

**Related Issue** : #1820 

### How Has This Been Tested?

1. create workbench with extended connection
2. check icon

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kyungtaak** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
@eltriny 
1. The icon has not changed in the workbench.
metatron_Discovery_및_myDesk

2. No third icon applied
metatron_Discovery_및_DevTools_-_52_231_184_135_8186_app_v2_workspace

**Comment by eltriny** [comment]
@ufoscw 작업된게 잘못 올라갔네요. 다시 커밋했습니다.

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
@metatron-app/design 
이미지 검수 요청드립니다.

**Pull request merged**
