### PR TITLE
#1227 Fix scroll ui in datasource

### PR DESCRIPTION
**Pull request by brandon-wonjune**
### Description

실제 스크롤되는 영역과 스크롤의 위치가 다른현상 수정

**Related Issue** : 

#1227 

### How Has This Been Tested?

1. 데이터소스 목록 > 스크롤 위치 확인
2. 데이터소스 생성 > 생성 타입 선택 팝업 > 스크롤 위치 확인
3. 데이터소스 생성 (file) > 파일 선택 > 스크롤 위치 확인
4. 데이터소스 생성 > config 설정 스탭 > 스크롤 위치 확인
5. 데이터소스 생성 > ingestion 설정 스탭 > 스크롤 위치 확인
6. 데이터소스 생성 > 생성 완료 스탭 > 스크롤 위치 확인
7. 데이터 커넥션 생성 > 스크롤 위치 확인
8. 데이터 커넥션 수정 > 스크롤 위치 확인

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project. _it will be added soon_
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kyungtaak** [comment]
run build
deploy to 5

**Comment by kyungtaak** [comment]
@brandon-wonjune Can you resolve the conflict?

**Comment by brandon-wonjune** [comment]
@kyungtaak resolved conflict

**Comment by kyungtaak** [comment]
run build
deploy to 5

**Comment by minjung-cho** [comment]
The areas shown in the two screenshots below are too wide. Please check the design guide.

When uploading Excel file
스크린샷 2019-04-16 오후 4 32 43

Schema configuration steps
스크린샷 2019-04-16 오후 4 33 11

**Comment by alchan-lee** [comment]
run build
deploy to 5

**Comment by alchan-lee** [comment]
run build
deploy to 5

**Comment by brandon-wonjune** [comment]
@minjung-cho fixed css

**Comment by kyungtaak** [comment]
run build
deploy to 5

**Comment by kyungtaak** [comment]
run build
deploy to 5

**Comment by brandon-wonjune** [comment]
@AnnieHwang please try agian
스크린샷 2019-04-18 오전 9 58 58

**Comment by kyungtaak** [comment]
@brandon-wonjune I checked to display normally. (reported from @AnnieHwang)
but, I think metatron engine view is not fixed. it's no requirement, but could you fix it?
image

**Comment by brandon-wonjune** [comment]
@brandon-wonjune create datasource druid engine, fixed

스크린샷 2019-04-18 오전 11 20 07

**Comment by kyungtaak** [comment]
run build
deploy to 5

**Comment by kyungtaak** [comment]
run build
deploy to 5

**Pull request merged**
