### PR TITLE
#2592 Contents in Column List of Metadata Management and Exploration Data Do Not Match 

### PR DESCRIPTION
**Pull request by thinkcsww**
fix explore metadata detail column tab's type column

### Description

Fix Explore metadata details's column tab's type column display error

**Related Issue** : 

#2592 

### How Has This Been Tested?

1. Exploration -> Data -> click any data 
2. click columns tab
3. check type column show proper data
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
delpoy to 1

**Comment by ufoscw** [comment]
run build
deploy to 1

**Comment by ufoscw** [comment]
@thinkcsww 
Does not match.

1. Metadata management
metatron_Discovery

2. Exploration
metatron_Discovery

**Comment by thinkcsww** [comment]
@ufoscw 
Modified.

**Comment by ufoscw** [comment]
run build
deploy to 1

**Comment by ufoscw** [comment]
run build
deploy to 1

**Comment by ufoscw** [comment]
@thinkcsww 
For fields that cannot be modified, please turn off the mouseover color inversion and the hand cursor function.
Type column: mouseover color inversion
Code Table Column: Hand Cursor

**Comment by thinkcsww** [comment]
@ufoscw 
About type column, what is the mouseover color inverison ???

**Comment by ufoscw** [comment]
@thinkcsww 
Please remove bg of unmodifiable column when mouse over
metatron_Discovery

**Comment by thinkcsww** [comment]
@ufoscw 
Modified

I can't see that symptom when i test with chrome, but i found it while i'm taking a video and convert to gif to show you. In gif image i can see that.

**Comment by ufoscw** [comment]
run build
deploy to 1

**Comment by ufoscw** [comment]
@thinkcsww 
Your edits are different from what I reported.
Disable mouse hover style changes like any other column.

**Comment by thinkcsww** [comment]
@ufoscw 
I found in type column cursor shape is 
image

Do you mean i should change cursor shape to this? 
image

**Comment by ufoscw** [comment]
@thinkcsww 
What I mean is not the cursor, but the background and border.
Depending on your monitor, you may not be able to recognize it.
Sep-25-2019 10-03-06

1. normal
metatron_Discovery

2. mouse hover (changed bg and appeared border)
metatron_Discovery

**Comment by thinkcsww** [comment]
@ufoscw 
Modified
image

**Comment by ufoscw** [comment]
run build
deploy to 1

**Pull request merged**
