### PR TITLE
#2805 Improved overview screen on data exploration

### PR DESCRIPTION
**Pull request by eltriny**
### Description

1. If data is of type datasource, the first dashboard thumbnail is shown. (removed)
2. 'No data' notification label required when no data
3. The font size of the title is too large. (I think 22px seems reasonable) => it's a publishing issue.
4. Catalog panel changed
Caroussel UI
If there is no 1depth, no path should be indicated (In case of 'favorite catalog')
'All catalog' panel is activated on first entry

**Related Issue** : #2805 

### How Has This Been Tested?

1. Check if 'No Data' is displayed normally on the main screen.
2. Make sure the left panel is changed to Caroussel
3. Check if the font size of the title has changed

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 3

**Comment by ufoscw** [comment]
> 4\. Catalog panel changed
>     Caroussel UI
>     If there is no 1depth, no path should be indicated (In case of 'favorite catalog')
>     'All catalog' panel is activated on first entry

" 'All catalog' panel is activated on first entry" is not applied.

**Comment by eltriny** [comment]
@ufoscw 
Modified

**Comment by minhyun2** [comment]
deploy to 3

**Pull request merged**
