### PR TITLE
#3907 datasource mapbox preview

### PR DESCRIPTION
**Pull request by eltriny**
### Description
Displaying a preview of location data using mapbox in the data source column detail menu

**Related Issue** : #3907 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Review by ufoscw — APPROVED** [review]

**Pull request merged**
