### PR TITLE
Fix error for java 11/12 compatibility

### PR DESCRIPTION
**Pull request by kyungtaak**
### Description
Fixed error for java 11/12 compatibility.
- update Hibernate ORM(5.2.12.Final -> 5.4.3.Final) & Hibernate Search (5.5.5.Final -> 5.11.1.Final) version 
- upgrade commons-lang3 version (3.5 -> 3.8.1) 

**Related Issue** : #1704 

### How Has This Been Tested?
All of the default functions were tested search as Ingestion, Dashboard

#### Need additional checks?
All of the data crud processing must be checked.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by kyungtaak** [comment]
run build
deploy to 6

**Comment by alchan-lee** [comment]
run build
deploy to 6

**Comment by alchan-lee** [comment]
run build
deploy to 6

**Comment by alchan-lee** [comment]
run build
deploy to 6

**Pull request merged**
