### PR TITLE
fix create dashboard error

### PR DESCRIPTION
**Pull request by eltriny**
### Description
1. Deleted without confirmation popup even though the data source is related to other data sources
2. When re-entering the data source selection popup, the list is displayed with the previously set type filter applied.
3. Manage Scheme> Join Popup> Join Type and Join Key Configuration UI Exposed by Default
4. Manage Scheme> Join Popup> Select Columns> Select Add Join Key> Enable Add Button Even When Column Types Are Different

**Related Issue** : 

METATRON-2840
METATRON-2844
METATRON-2847
METATRON-2849

### How Has This Been Tested?

1. When creating a dashboard, confirm that a confirmation window appears when deleting a data source while connected between data sources.
2. When creating the dashboard, make sure that the previous filter is initialized when you bring up the data source selection popup.
3. When creating the dashboard, verify that the preview area in the Join popup is hidden and displayed after selecting the join key.
4. When creating the dashboard, verify that the type check for the join key is done in the join popup.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by kyungtaak** [comment]
@AnnieHwang please check below statement.
image

**Comment by kyungtaak** [comment]
@eltriny I knew that a column to join can select in below view, but I can't!
image

**Comment by eltriny** [comment]
@kyungtaak 
대시보드쪽 join 에서는 컬럼 선택을 구현한 적이 없었습니다. 새로 추가된건가요?

**Comment by kyungtaak** [comment]
@eltriny 아 아닙니다. 제가 착각했네요.

**Pull request merged**
