### PR TITLE
#1784 line chart custom color initialized

### PR DESCRIPTION
**Pull request by eltriny**
### Description
If you change the line chart to Custom Color and then add dimension, the color will return to the initial palette.

**Related Issue** : #1784 

### How Has This Been Tested?

1. create line chart
2. color setting > cusom color setting
3. change color
4. add dimension

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kyungtaak** [comment]
run build
deploy to 4

**Comment by alchan-lee** [comment]
Apr-17-2019 10-23-03

사용자 색상 설정 활성화를 해도 아무런 이벤트가 안걸리는 것 같습니다.

**Comment by eltriny** [comment]
@alchan-lee 수정했습니다.

**Comment by alchan-lee** [comment]
run build
deploy to 4

**Comment by alchan-lee** [comment]
run build
deploy to 4

**Comment by alchan-lee** [comment]
@eltriny 
measure를 추가하면 사용자 색상 설정탭에는 추가가 안되네요,
기존에는 되었던거로 봐서는 사이드이펙트 같습니다.. 😢 

Apr-17-2019 18-57-00

**Comment by eltriny** [comment]
@alchan-lee 수정했습니다.

**Comment by alchan-lee** [comment]
run build
deploy to 4

**Comment by alchan-lee** [comment]
run build
deploy to 4

**Pull request merged**
