### PR TITLE
F#3641 custom color data grid

### PR DESCRIPTION
**Pull request by eltriny**
### Description

Custom color for each measure in DataGrid

**Related Issue** : #3641 

### How Has This Been Tested?

1. Grid chart creation
2. Color settings for measurements on the shelf
3. Check the dashboard

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Review by ufoscw — APPROVED** [review]

**Review by minhyun2 — APPROVED** [review]

**Pull request merged**
