### PR TITLE
F#805 add file upload location

### PR DESCRIPTION
**Pull request by ksparknot**
### Description

If the dataset has file type, user should choose a destination

**Related Issue** : 

[#805](https://github.com/metatron-app/metatron-discovery/issues/805)

### How Has This Been Tested?

1. create a file dataset
2. upload a file and select a upload location
3. if the dataset is created, check the property 'fileType'

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by joohokim1** [comment]
run build
deploy to 4

**Comment by mh0203** [comment]
At Testbed 4 HDFS dataset is not created.

**Comment by mh0203** [comment]
PrepDatasetFileService.java의 getPreviewLinesFromFileForDataFrame()에서 오류가 발생합니다.
upload된 파일을 불러오려고 하는데, HDFS 경로가 아닌 Local경로가 들어와서 file not found가 발생하는 것같습니다.
실제로도 HDFS에는 파일이 없고 local에만 생성되어있네요.

**Comment by joohokim1** [comment]
run build
deploy to 4

**Comment by joohokim1** [comment]
run build
deploy to 4

**Comment by joohokim1** [comment]
I fixed a typo-like bug.
And I found that there is no consideration about filekey missing, so I defined an error code for it.

_Typo성 버그가 있어서 고쳐서 넣었습니다. 넣는 김에 filekey가 없는 경우에 대해 따로 처리가 없어서, error code를 하나 정의했습니다._

**Pull request merged**
