### PR TITLE
F#917 fixed error deleting multiple expressions

### PR DESCRIPTION
**Pull request by sang-hee-lee**
### Description

1. delete expression corresponding to delete button position
2. warning messages when adding rules without expressions(window, pivot, aggregate, set, derive)

**Related Issue** : 

#917 
MT-69
MT-70
MT-71

### How Has This Been Tested?

1.1. menu > MANAGEMENT > DataPreparation
1.2. click Dataflow > click Wrangled Data > Edit rules
1.3. add rule : window, pivot, aggregate
1.4. Add two or more expressions and click the Delete Expression button

2.1. menu > MANAGEMENT > DataPreparation
2.2. click Dataflow > click Wrangled Data > Edit rules
2.3. add rule : window, pivot, aggregate, set, derive
2.4. Check for warning messages when adding rules without expressions

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kyungtaak** [comment]
run build
deploy to 3

**Comment by sang-hee-lee** [comment]
I found an error and will reopen it after fixing it.

**Comment by sang-hee-lee** [comment]
An error has been fixed. Request a build.

**Comment by ufoscw** [comment]
run build
deploy to 5

**Pull request merged**
