### PR TITLE
Update zh.json

### PR DESCRIPTION
**Pull request by qinchaofeng**
Optimizing Translation Contents

### Description

Optimizing Translation Contents

**Related Issue** : 
https://github.com/metatron-app/metatron-discovery/issues/291

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by kyungtaak** [comment]
Thank you for your contribution! But.. I'm not sure if we can verify it properly. Maybe we should believe in you and then merge. :) Anyway, I'll check with my colleagues as much as we can.

**Comment by kyungtaak** [comment]
run build
deploy to 1

**Comment by AnnieHwang** [comment]
@kyungtaak I cannot use Chinese on the test1 server. However, i can use Chinese on other test servers. Please check the test1 server.

**Comment by minhyun2** [comment]
@qinchaofeng There is no double quotation mark on the 1009 line.
Could you check it again? Thanks in advance for your response.
metatron-discovery_zh_json_at_patch-1_·_qinchaofeng_metatron-discovery

**Comment by qinchaofeng** [comment]
@minhyun2 sorry for that, I have added the double quotation,Thanks.

**Comment by minhyun2** [comment]
run build
deploy to 6

**Comment by minhyun2** [comment]
run build
deploy to 6

**Comment by minhyun2** [comment]
@qinchaofeng I am sorry to have deleted your comment on my mistake.
Thank you for your contribution.

**Comment by kyungtaak** [comment]
run build
deploy to 6

**Pull request merged**
