### PR TITLE
#2214 permission schema deleted and set default permission schema

### PR DESCRIPTION
**Pull request by minhyun2**
### Description
If a permission schema deleted, linked workspaces to the schema is setted to the default permission schema.

**Related Issue** : #2214 

### How Has This Been Tested?
1. Create a shared workspace.
2. Create a new permission schema.
3. Set the permission schema to the workspace.
4. Delete the permission schema.
5. Check the workspace to see if it is set to the default permission schema.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
run build
deploy to 5

**Comment by kyungtaak** [comment]
@minhyun2 It wasn't changed! I created a schema that includes "test" role, I set schema i created to the shared workspace named "test Schema", I assigned "Test!" role to user1 and "Editor" to user2, and then  I deleted schema i created.
I expected two users to be automatically set to the default role in the default schema. but..
image

**Comment by minhyun2** [comment]
run build
deploy to 5

**Comment by minhyun2** [comment]
run build
deploy to 5

**Comment by minhyun2** [comment]
run build
deploy to 5

**Comment by minhyun2** [comment]
run build
deploy to 5

**Comment by minhyun2** [comment]
run build
deploy to 5

**Comment by minhyun2** [comment]
run build
deploy to 5

**Pull request merged**
