### PR TITLE
fn-fix_explore_data_ui_error

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

3023, 3031
fix ui overlap
**Related Issue** : 

METATRON3023
METATRON3031

### How Has This Been Tested?

1. Explore Data
2. check ui is overlap
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 4

**Comment by ufoscw** [comment]
run build
deploy to 4

**Comment by thinkcsww** [comment]
@ufoscw
Modified - display null in recommended card

**Comment by ufoscw** [comment]
run build
deploy to 4

**Comment by ufoscw** [comment]
run build
deploy to 4

**Comment by ufoscw** [comment]
run build
deploy to 4

**Comment by ufoscw** [comment]
@eltriny 
Ellipsis disappears in IE
Windows_7

**Comment by eltriny** [comment]
@ufoscw 수정했습니다.

**Comment by ufoscw** [comment]
run build
deploy to 4

**Pull request merged**
