### PR TITLE
#3637 add subtotal grid

### PR DESCRIPTION
**Pull request by eltriny**
### Description

I need the subtotal function of the grid chart.

**Related Issue** : #3637 

### How Has This Been Tested?

1. Go to the chart creation screen.
2. Create a grid chart by placing at least 2 dimension values on the shelf.
3. In the Totals panel, check if the subtotal option is working properly.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Review by ufoscw — APPROVED** [review]

**Pull request merged**
