### PR TITLE
F#1296 Fix information in snapshot detail

### PR DESCRIPTION
**Pull request by paigechoi**
### Description

Information in snapshot detail popup and snapshot list is fixed

**Related Issue** : 

#1296 

### How Has This Been Tested?

1 . Go to snapshot list -> Check if snapshot type is FILE(CSV) or FILE(JSON)
image

2 . Go to snapshot detail popup 
2-1. Check if snapshot type is FILE(JSON) or FILE(CSV)
2-2. Check if you can see FILE URI
2-3. CHECK if row and column is on the separate line
image

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### Additional Context

1 . Go to dataset detail -> check if summary (row and column is on the separate line)
1 . Go to dataflow detail -> click one imported datset -> check dataflow info panel -> check if summary (row and column is on the separate line)
image

### CODE REVIEW

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by paigechoi** [comment]
@joohokim1 Something went wrong. Let me know if I have to fix it...

**Comment by joohokim1** [comment]
run build
deploy to 1

**Pull request merged**
