### PR TITLE
#3871 added terms and skip approval register user

### PR DESCRIPTION
**Pull request by eltriny**
### Description
added terms and skip approval register user

**Related Issue** : #3871 

### How Has This Been Tested?

1. Register additional information in Client Details.
2. Access the external user registration screen and check whether the terms related to the terms and conditions are displayed.
3. Check if user registration is possible without approval process.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Review by ufoscw — APPROVED** [review]

**Comment by kyungtaak** [comment]
@eltriny I'd like to know more about the attribute information added to the "additional Information" item and how to test it.

**Comment by ufoscw** [comment]
deploy to 1

**Comment by kyungtaak** [comment]
@eltriny @ufoscw There is no cancel button as below.
image

**Comment by kyungtaak** [comment]
@eltriny you need to check resource bundle.
image

**Review by ufoscw — APPROVED** [review]

**Review by pygman86 — APPROVED** [review]

**Pull request merged**
