### PR TITLE
#1798 decide column count only by the first line

### PR DESCRIPTION
**Pull request by joohokim1**
### Description
Now, the first line's column count is the column count of the file.
The column count had been defined by max column count of the sample rows.
When we talk about "column count", it shouldn't be changed without the change of the file itself.

**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1798

### How Has This Been Tested?
1. Import [dynamic_colcnt.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3650938/dynamic_colcnt.csv.txt)
2. Column count should be 3 like this:
스크린샷 2019-09-25 오후 3 56 24
3. When you manually set the column count as 5, it has to be like this:
스크린샷 2019-09-25 오후 3 56 46

#### Need additional checks?
Yes.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by ufoscw** [comment]
@joohokim1 
Do we need to limit column count maximums?

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
run build
deploy to 1

**Pull request merged**
