### PR TITLE
#1104 Sorting error in gauge chart

### PR DESCRIPTION
**Pull request by juheeko9**
### Description
게이지차트의 오름차순 / 내림차순의 미동작 에러를 해결합니다.

**Related Issue** : #1104 

### How Has This Been Tested?
1. 차트화면에서 게이지차트를 선택합니다.
2. 선반에 diemsnion / measure를 각각 하나씩 올립니다.
3. measure의 오름차순 / 내림차순에 따라 차트가 정렬되는지 확인합니다.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 4

**Comment by ufoscw** [comment]
@juheeko9 
devtools_-_metatron-web-04_8188_app_v2_workbook_98a17add-2df8-46a0-852f-5097d387b498_ _metatron_discovery

**Comment by juheeko9** [comment]
@ufoscw 수정하였습니다.

**Comment by alchan-lee** [comment]
run build
deploy to 4

**Pull request merged**
