### PR TITLE
#2651 Uppercase table name of postgresql to create dataset

### PR DESCRIPTION
**Pull request by ksparknot**
### Description
Dataset had a bug when postgresql table name contains uppercase letters

Fixed this bug.

**Related Issue** : 
[#2651](https://github.com/metatron-app/metatron-discovery/issues/2651)

### How Has This Been Tested?

1. Create connection to postgresql
2. Create table with Upper case
ex) create table "Table1" (i int);
3. Create DataSet.
4. No error should occur.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ksparknot** [comment]
run build
deploy to 3

**Comment by ufoscw** [comment]
@ksparknot 
The same error occurs when there is an uppercase letter in the schema name.

**Comment by ksparknot** [comment]
run build
deploy to 3

**Comment by ksparknot** [comment]
> @ksparknot
> The same error occurs when there is an uppercase letter in the schema name.


Schemas are also handled to have uppercase letters

**Comment by joohokim1** [comment]
There was nothing to merge onto 3.3.x.
The changes have probably done by another PR.

**Pull request merged**
