### PR TITLE
#3687 change datasource in dashboard

### PR DESCRIPTION
**Pull request by eltriny**
### Description

Add data source replacement function.

**Related Issue** : #3687 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Review by ufoscw — DISMISSED** [review]

**Comment by ufoscw** [comment]
deploy to 1

**Review by minhyun2 — APPROVED** [review]

**Review by ufoscw — APPROVED** [review]

**Pull request merged**
