### PR TITLE
#2240 change to url mode when creating notebook server

### PR DESCRIPTION
**Pull request by minhyun2**
### Description
1. Change to url mode when creating notebook server (#2240)
1. Initialize selection value when selecting notebook server in workspace (#2170)

**Related Issue** : #2240, #2170 

### How Has This Been Tested?
1. Create notebook server with url. (It supports http and https)
image

2. Reset notebook server in workspace
image

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by AnnieHwang** [comment]
@minhyun2 Error label is incorrect when connection is wrong.
image

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
> @minhyun2 Error label is incorrect when connection is wrong.
> image

@AnnieHwang 
If you enter a URL without including the protocol(http or https), the following message is displayed.
-> Invalid URL. Please check URL

**Comment by AnnieHwang** [comment]
@minhyun2 It's good :) I will write in the wireframe.

**Comment by AnnieHwang** [comment]
@minhyun2 
If the error is a wrong URL and I am in error, it should look like this:
A common UI policy shows, an error message at the bottom of the input and the input should be highlighted. (하나의 인풋값에 대한 에러인 경우, 해당 인풋이 하이라이트 되어야 하며 해당 인풋 하단에 에러명이 나타나야하니다.)
The toast UI represents a definition of the action that occurs  actions (such as when the creation is poor or the creation is good) after the creation popup is closed
(토스트는 생성이 잘 안되었거나, 생성이 잘 된 경우와 같이 생성팝업이 닫힌 후 일어나는 액션에 대한 정의를 표현합니다.)
image

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
@minhyun2 
can't add notebook server.
url : http://metatron-web-04:8888
metatron_Discovery

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
> @minhyun2
> can't add a notebook server.
> url : http://metatron-web-04:8888
> metatron_Discovery

I modified url validation to be checked on the server side.

**Comment by ufoscw** [comment]
@AnnieHwang 
Users will accept the meaning of the "Reset" button as "return to the state before modification".
Please comment on modifying the button label to "None". (ko:설정 안함)

**Comment by AnnieHwang** [comment]
@ufoscw Where is the "Reset" button?

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by kyungtaak** [comment]
@minhyun2 워크스페이스내 확인 부탁드립니다설정 화면내.. url 도 말줄임에 마우스오버시 툴팁을 넣어야할것 같아요.
image

**Comment by minhyun2** [comment]
run build
deploy to 2

**Pull request merged**
