### PR TITLE
F#2496 show message for error case

### PR DESCRIPTION
**Pull request by ksparknot**
### Description
When user uploads a wrong formatted file, 
error message should be shown. about unsupported file or invalid format

and
There are included issues because there is work on the same area of ​​the same page.
(the page of uploading lineage is made according to the planing document.)

**Related Issue** :
[#2496 ](https://github.com/metatron-app/metatron-discovery/issues/2496) 
METATRON-2995
METATRON-2998
METATRON-2999
METATRON-3001

### How Has This Been Tested?
1. upload an unsupported file like .json
2. upload a file has invalid format. (has no metaId and metaName)
error message should be shown

and the pages will be shown as planning

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by joohokim1** [comment]
run build
deploy to 4

**Comment by joohokim1** [comment]
Below is the essential comment in https://github.com/metatron-app/metatron-discovery/issues/2496 about this PR :

this issue is completed.
but new issues are included because there is work on the same page as the planning document.

included codes are according the planning document.

download sample division
invalid format division
uploaded file name division
row count of uploaded lineage

**Comment by joohokim1** [comment]
run build
deploy to 5

**Comment by joohokim1** [comment]
run build
deploy to 5

**Comment by ksparknot** [comment]
run build
deploy to 5

**Comment by ksparknot** [comment]
run build
deploy to 5

**Comment by joohokim1** [comment]
run build
deploy to 5

**Comment by ksparknot** [comment]
run build
deploy to 5

**Comment by joohokim1** [comment]
Closing PR because this matter will be processed by an regular issue later, but by PR-only patch.
There are tons of consideration.

I think we have to start another branch, and cherry-pick the changes of this branch.

**Pull request closed without merging**
