### PR TITLE
#2954 Improvements for real-time dashboard

### PR DESCRIPTION
**Pull request by eltriny**
### Description

When applying sync to an entire dashboard, not all widgets need to be applied.
Requires data processing of chart widget for real time environment.

**Related Issue** : #2954 

### How Has This Been Tested?

1. Create a dashboard using a real-time data source.
2. Set the data synchronization time on the dashboard edit screen.
3. Check if the sync button is activated and working for each widget.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 4

**Comment by alchan-lee** [comment]
deploy to 4

**Comment by ufoscw** [comment]
@eltriny 
When I click on the chart background, I get the following console error. Is this a side effect?
DevTools_-_52_231_153_96_8188_app_v2_workbook_09efadcc-750d-42ba-af19-47e58154dabc

**Comment by kyungtaak** [comment]
@eltriny You need to add and modify additional features.
- It should add the sync control panel in the upper area of ​​the dashboard.
- The on-off icon doesn't have to save in view mode.

**Comment by eltriny** [comment]
@kyungtaak 
As for the top filter, I told you to go to another issue.

**Comment by kyungtaak** [comment]
deploy to 4

**Pull request merged**
