### PR TITLE
Bug fix in dataprep

### PR DESCRIPTION
**Pull request by paigechoi**
### Description

Fix bugs in dataprep

**Related Issue** : 

MT-192
MT-165
MT-175
MT-185
MT-186

### How Has This Been Tested?

1. (IE) Dataflow detail -> click imported dataset -> dataset swap -> click one dataset -> check if selected row css is not broken
image

2. Dataflow main grid -> join -> click list view (left) -> check if all icon is shown (all types) 
image

3. Dataflow main grid -> join -> click list view (right) -> check if css is not broken
image

4. Dataflow main grid -> join -> preview -> click on type -> check if you can see type list popup 
image

5. Dataflow tab -> check if first column has a labe of `Name` instead of `Dataflow`

6. Dataflow main grid -> click types in the top right corner -> see if you can see the type list popup 
image

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by joohokim1** [comment]
run build
deploy to 2

**Comment by paigechoi** [comment]
FIxed number 3 bug

**Comment by kyungtaak** [comment]
run build
deploy to 2

**Comment by kyungtaak** [comment]
run build
deploy to 2

**Pull request merged**
