### PR TITLE
F#2132 detail explore metadata

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

Detail Explore Metadata 
Get TopUser, Histories, Recently Queries using api

**Related Issue** : 

#2132 

### How Has This Been Tested?

1. Using LNB go to explore data page
2. Click Metadata Card 
3. Check data is shown properly

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 5

**Comment by ufoscw** [comment]
run build
deploy to 5

**Comment by eltriny** [comment]
@ufoscw 
확인 부탁드립니다.

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
@thinkcsww 
1. DataSource Type - Workbook Link
metatron_Discovery

2. DataSource Type - need more column width for Date type
metatron_Discovery

3. Database Type - remove Type Column. 
And there is no "See All List" button and 20 is shown in the grid, not 5.
metatron_Discovery

4. StagingDB Type - Clicking Card does not bring up the detail screen.
DevTools_-_52_231_184_135_8186_app_v2_exploredata_view_및_metatron_Discovery

**Comment by eltriny** [comment]
@ufoscw 확인부탁드립니다.

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
run build
deploy to 2

**Pull request merged**
