### PR TITLE
Fix user image display error and icon display error

### PR DESCRIPTION
**Pull request by eltriny**
### Description

1.Exploration> Data Creator User thumbnail not shown
2. The Exploration> Data Creator> Detail data list's sorting default is Created Time (descending), which is indicated by the Sort Name in the grid header.
3. Delete icon is overlaid when hovering over Management> Metadata Database, StagingDB

**Related Issue** : 

### How Has This Been Tested?

1.Explore Exploration> Data Creator User Image Thumbnail
2. Verify that the sort defaults in the Exploration> Data Creator> Detail data list are displayed in descending order at Created Time.
3. Check if the delete icon is displayed normally when hovering over Management> Metadata Database, StagingDB.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 3

**Comment by ufoscw** [comment]
@eltriny 
2. Please remove space in parameter
createdTime, desc (X)
createdTime,desc (O)
DevTools_-_52_231_184_135_8187_app_v2_exploredata_favorite_creator_admin_size_20_page_0_creatorContains_admin_sort_createdTime_asc

3. not fixed.
metatron_Discovery

**Comment by eltriny** [comment]
@ufoscw 
Please check

**Comment by ufoscw** [comment]
deploy to 3

**Pull request merged**
