### PR TITLE
#1647 fix dataset name max length

### PR DESCRIPTION
**Pull request by paigechoi**
### Description

Allow upto 150 characters for dataset name

**Related Issue** : 

#1647 

### How Has This Been Tested?

Check #1647 for details
** Check dataset name length when creating dataset

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by joohokim1** [comment]
run build
deploy to 3

**Comment by joohokim1** [comment]
run build
deploy to 3

**Comment by joohokim1** [comment]
run build
deploy to 3

**Comment by paigechoi** [comment]
[멀티파일 업로드 시 이름 적는 부분에...인풋 높이가 디자인과 맞지 않음](https://trello.com/c/4N03bA6Q/23-%EB%A9%80%ED%8B%B0%ED%8C%8C%EC%9D%BC-%EC%97%85%EB%A1%9C%EB%93%9C-%EC%8B%9C-%EC%9D%B4%EB%A6%84-%EC%A0%81%EB%8A%94-%EB%B6%80%EB%B6%84%EC%97%90%EC%9D%B8%ED%92%8B-%EB%86%92%EC%9D%B4%EA%B0%80-%EB%94%94%EC%9E%90%EC%9D%B8%EA%B3%BC-%EB%A7%9E%EC%A7%80-%EC%95%8A%EC%9D%8C)

**Pull request merged**
