### PR TITLE
#3181 fix script error when pie chart and table chart contain alias

### PR DESCRIPTION
**Pull request by minhyun2**
### Description

fix script error when pie chart and table chart contain alias

**Related Issue** : #3181 

### How Has This Been Tested?

1. Go to a dashboard with 'Sales' datasource.
2. Create a text table chart.
3. Place Category and Sub-category on the second shelf and set the alias
and In the Common Setting, set the Text Style Aggregation Column to On (Horizonal).
4. Alias ​​is applied.
5. Create a pie chart
6. Place Category and Profit on the shelf and set the alias.
7. See without error

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 2

**Comment by ufoscw** [comment]
@minhyun2 
If you select "Original Data" when drawing a table chart with sales data, the following console error will occur.
WebServerWatch
WebServerWatch

**Comment by minhyun2** [comment]
deploy to 2

**Comment by kyungtaak** [comment]
@minhyun2 We confirmed normal operation regard to "Alias" on the shelf. I don't know if it's related to this issue, but if I set Alias ​​in the data source itself, it should look like this:
image

**Comment by minhyun2** [comment]
@kyungtaak The alias setting of the datasource itself is not related to this issue. However, we will find ways to improve it by managing it with new issues.

**Pull request merged**
