### PR TITLE
#2857 Improve preview stage of progress on stream datasource creation

### PR DESCRIPTION
**Pull request by minhyun2**
### Description

Improve preview stage of progress on stream datasource creation

**Related Issue** : #2857 

### How Has This Been Tested?

1. Create a new stream datasource using kafka data in csv format.
2. Upload the csv file to create the datasource schema.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 6

**Comment by minhyun2** [comment]
deploy to 6

**Comment by alchan-lee** [comment]
image

"Please" resolve this tiny misspelled issue 😅 
From `Plase` to `Please`

**Comment by minhyun2** [comment]
deploy to 6

**Pull request merged**
