### PR TITLE
#2008 improve UX for function selection area on user-defined field view

### PR DESCRIPTION
**Pull request by minhyun2**
### Description
Improve UX for function selection area on user-defined field view

**Related Issue** : #2008 

### How Has This Been Tested?
1. Go to workbook and create or edit Chart.
2. Move to create custom-filed view.
3. Check tUX for function selection area on user-defined field view.

#### Need additional checks?
Check both language. (If your language is Chinese, it is displayed in English.)

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by AnnieHwang** [comment]
@minhyun2 The design and implementation results are different. 
(Implementation Results)
image
(Design)
image

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by AnnieHwang** [comment]
@eltriny @koeun222 The design came out but the publishing didn't come out.
image

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by kyungtaak** [comment]
@minhyun2 good job! :)

**Pull request merged**
