### PR TITLE
F#2354 exploration menu change

### PR DESCRIPTION
**Pull request by ufoscw**
### Description
exploration menu change

**Related Issue** : #2354 

### How Has This Been Tested?
check Menu Label
 - Explore Data -> Exploration

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 1

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
@eltriny 
Please check css issue.

1. Only the top title has a different font. You need to treat it like any other text. Fonts are strange when in Korean.
DevTools_-_52_231_184_135_8186_app_v2_exploredata_view_및_metatron_Discovery


2. please remove selected BG.
metatron_Discovery_및_DevTools_-_localhost_4200_app_v2_management_metadata_metadata

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
@eltriny 
Fixing css causes vertical alignment errors in other menus.
metatron_Discovery

**Comment by eltriny** [comment]
@ufoscw 수정했습니다.

**Comment by ufoscw** [comment]
run build
deploy to 2

**Pull request merged**
