### PR TITLE
#3544 Added member sign-up to external login page and added organization input function when registering as a member

### PR DESCRIPTION
**Pull request by eltriny**
### Description
Added member sign-up to external login page and added organization input function when registering as a member

**Related Issue** : #3544 

### How Has This Been Tested?
1. Check if there is a sign up button on the external login page.
2. Make sure there is an Organization field on the signup page.
3. Check if the organization code is checked when entering the organization.
4. Check if membership registration is successful.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Review by minhyun2 — APPROVED** [review]

**Pull request merged**
