### PR TITLE
F#484 rule builder error

### PR DESCRIPTION
**Pull request by paigechoi**
### Description

In editing mode switch to builder/switch to editor button disappears.
Allow editor mode when editing rule.

**Related Issue** : 

#484 

### How Has This Been Tested?

Go to dataflow main grid
Add one rule. Edit that rule. 
Check if you can see the switch to builder/editor button

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by joohokim1** [comment]
run build
deploy to 4

**Comment by mh0203** [comment]
run build
deploy to 4

**Comment by mh0203** [comment]
run build
deploy to 4

**Comment by joohokim1** [comment]
Rule builder로 window를 실행하면 rule string이 아래처럼 들어가네요.
`window value: [rolling_sum(column7, 2, 2)] group: column2 order: column1`
`window value: [rolling_sum(column7, 2, 2), lead(column9, 1)] group: column2 order: column1`
되긴 되는데...
`window value: rolling_sum(column7, 2, 2) group: column2 order: column1`
`window value: rolling_sum(column7, 2, 2), lead(column9, 1) group: column2 order: column1`
위처럼 룰이 만들어질 수는 없을까요?

**Comment by joohokim1** [comment]
Approved because the original purpose of this issue has been achieved.

_본 이슈의 원래 목적은 이루었다고 볼 수 있으니 일단 approve를 합니다._

**Comment by joohokim1** [comment]
run build
deploy to 4

**Comment by joohokim1** [comment]
run build
deploy to 4

**Pull request merged**
