### PR TITLE
Internationalize mailing template

### PR DESCRIPTION
**Pull request by alchan-lee**
### Description

Internationalize mailing template
- Approved user registration
- Rejected user registration
- Change password

**Related Issue** : 

#1933 

### How Has This Been Tested?

1. Create a new account in the login page with a valid e-mail
2. Check your mailbox and confirm the messages are translated properly

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by alchan-lee** [comment]
run build
deploy to 4

**Comment by alchan-lee** [comment]
run build
deploy to 4

**Comment by ufoscw** [comment]
@alchan-lee 
The title and contents of the welcome message are strange.
받은_편지함_7_738개의_메시지_

**Comment by alchan-lee** [comment]
run build
deploy to 2

**Comment by alchan-lee** [comment]
run build
deploy to 2

**Comment by alchan-lee** [comment]
run build
deploy to 2

**Comment by alchan-lee** [comment]
@ufoscw 
thank you for good advice.
I added a resolved change on the branch.

**Pull request merged**
