### PR TITLE
fn-fix_workspace_name_duplication_error

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

fix name duplication check
**Related Issue** : 

METATRON-2856

### How Has This Been Tested?

1. click workspace list 
2. click create workspace
3. check name duplciation checking works well
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by kyungtaak** [comment]
@thinkcsww This issue seems to be more effective if there is a separate api that checks for duplicates. 
@minhyun2 Can you make related api?

**Comment by ufoscw** [comment]
run build
deploy to 3

**Comment by minhyun2** [comment]
@thinkcsww @kyungtaak 
Every time you enter a key, there is an ajax request, which is inefficient. I will try to improve it.

**Comment by minhyun2** [comment]
run build
deploy to 3

**Pull request merged**
