### PR TITLE
#363 fix quartile values in data preview and column detail

### PR DESCRIPTION
**Pull request by 9bow**
### Description
fixed lower / upper quartile values in data preview & column detail.
in detail, changed position of lower and upper quartile values.

**Related Issue** : 
#363 

### How Has This Been Tested?

follow the "reproduce" section in issue #363 
1. 데이터 소스 관리 > 데이터 소스 목록 > 상세 보기
  or 대시보드 내 데이터 소스 상세 보기
1. "Column Detail" Tab 클릭
1. 측정값 선택 > "Statistic" 항목 확인
1. See error

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alchan-lee** [comment]
run build
deploy to 3

**Comment by alchan-lee** [comment]
@9bow 
헛, column-detail-data-source.component.ts 에 데이터소스 상세보기 화면 구현 로직이 들어갑니다 😄 

덕분에 다른 화면에서의 버그도 찾았군요

**Comment by 9bow** [comment]
@alchan-lee 
엄한 부분을 고쳤었네요;; 다시 빌드 부탁드립니다. (_ _)

**Comment by alchan-lee** [comment]
run build
deploy to 3

**Comment by alchan-lee** [comment]
run build
deploy to 3

**Pull request merged**
