### PR TITLE
#3049 In case of real-time dashboard, cache should not used

### PR DESCRIPTION
**Pull request by ufoscw**
### Description
Real-time dashboard should use queried data, not cached data when chart drawing.

**Related Issue** : #3049 

### How Has This Been Tested?
1. Create real-time dashboard.
2. turn on "Data sync" in dashboard edit.
3. turn on "Data sync" in widget tool bar.
4. should re-draw the chart every interval.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 3

**Comment by alchan-lee** [comment]
image

Works well with only one measure.
**But not updated as the second measure.**

**Comment by ufoscw** [comment]
deploy to 3

**Comment by alchan-lee** [comment]
Feb-05-2020 13-15-06
hmm.. still not updated.. 😭

**Comment by ufoscw** [comment]
deploy to 3

**Pull request merged**
