### PR TITLE
F#622 change settype selectbox

### PR DESCRIPTION
**Pull request by imsaaks**
### Description

Rule(setformat) editor modify
- create prep-select-box-custom
- modify settype and setformat rule

**Related Issue** : 

#622 

### How Has This Been Tested?

1. Create
① click Dataflow
② click Wrangled dataset
③ click Edit rule
④ select column
⑤ Add rule
⑥ command -> settype -> new type --> string
⑦ modify(input) Set Pattern

2. Modify
① click Dataflow
② click Wrangled dataset
③ click Edit rule
④ select Rule (ex) Change time type to string

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
timestamp_format_input_box

Additional modifications are required for the following:

1. Set keyboard focus to enable typing immediately after selecting an item
2. When filtering an item, use startsWith instead of contains (it does not need to be in the middle)
3. Remove custom format

_다음의 사항들에 대해 추가 수정이 필요합니다._

1. _항목을 선택한 후에 바로 typing이 가능하도록 keyboard focus 설정_
2. _항목을 filtering할 때, contains가 아닌 startsWith로 하도록 (중간에 해당 내용이 있어봐야 필요 없음)_
3. _Custom format 제거_

**Comment by imsaaks** [comment]
요청주신 아래 3가지 사항, 수정했습니다.

1.항목을 선택한 후에 바로 typing이 가능하도록 keyboard focus 설정
2. 항목을 filtering할 때, contains가 아닌 startsWith로 하도록 (중간에 해당 내용이 있어봐야 필요 없음)
3. Custom format 제거

**Comment by joohokim1** [comment]
run build
deploy to 4

**Comment by joohokim1** [comment]
run build
deploy to 4

**Comment by joohokim1** [comment]
run build
deploy to 4

**Comment by joohokim1** [comment]
Set keyboard focus to enable typing immediately after selecting an item --> NOT VERIFIED
Does it work?

**Comment by paigechoi** [comment]
We will reopen this pr when it's done

**Comment by imsaaks** [comment]
fixes the problem of gaps by unit of column (union)

add textinput focus setSelectionRange

**Comment by joohokim1** [comment]
run build
deploy to 5

**Comment by mh0203** [comment]
i'm not a reviewer, but it works well.

**Comment by imsaaks** [comment]
Focus is not possible during the initial selection step. May affect other actions.
However, after clicking the component, focus was applied.

**Pull request merged**
