### PR TITLE
#459 Hive query result showed 'No data' update

### PR DESCRIPTION
**Pull request by sting009**
### Description

 Hive query result showed 'No data' update

**Related Issue** : #459  

### How Has This Been Tested?

1. Go to workbench
2. excute query
select * from sample
3. See "No data" message
4. drawing grid as a result 

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 3

**Comment by alchan-lee** [comment]
run build
deploy to 3

**Comment by alchan-lee** [comment]
run build
deploy to 3

**Comment by ufoscw** [comment]
run build
deploy to 3

**Pull request merged**
