### PR TITLE
#2562 Support realtime datasource

### PR DESCRIPTION
**Pull request by minhyun2**
### Description

Support realtime datasource

**Related Issue** : #2562 

### How Has This Been Tested?

1. Create a datasource with stream
2. Input kafka server and choose topic
3. Check that the datasource is created and ingested normally.

#### Need additional checks?
https://metatron.app/2018/08/02/visualize-real-time-data-with-metatron-discovery/

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
run build
deploy to 4

**Comment by ufoscw** [comment]
@minhyun2 
```
[ERROR] 
[ERROR] ERROR in src/app/data-storage/data-source-list/create-data-source/stream-create-component/stream-preview/stream-preview.component.html(89,67): : Property 'sourceData' is private and only accessible within class 'StreamPreviewComponent'.
[ERROR] 
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! polaris2-ui@0.0.0 prod: `npm run package-reinstall && node --max_old_space_size=10240 ./node_modules/.bin/ng build --deploy-url /resource/ --output-hashing all --prod --base-href /app/v2/`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the polaris2-ui@0.0.0 prod script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /data1/jenkins/.npm/_logs/2019-10-15T04_45_23_670Z-debug.log
```

**Comment by minhyun2** [comment]
run build
deploy to 4

**Comment by minhyun2** [comment]
run build
deploy to 4

**Comment by alchan-lee** [comment]
It's a great feature I've been looking forward to! 👏 
and it seems to be working well 👏👏 

But I have suggestions for better functionality.
(I think It doesn't have to be resolved in this PR now, but it should be in the near future.)

---

1. It would be nice to provide a sample file when setting the format by file.
image


---

2. It is so hard to find a topic that I want to use.
I think searching is the best, but at least sorting should be supported.

image


---

3. When using the KafkaIndexing, ioConfig is important too.
But only support tuningConfig now by the advanced options. Setting ioConfig is not optional, it must be supported.

image

**Comment by minhyun2** [comment]
@alchan-lee 
First, I will modify the sorting of the Topic list.

**Comment by minhyun2** [comment]
run build
deploy to 4

**Comment by kyungtaak** [comment]
@minhyun2  

> 1. It would be nice to provide a sample file when setting the format by file.

Can I add a information phase? 
- "필요시 토픽에 전달될 형식의 파일을 업로드 할수 있다."
- "If necessary, you can upload a file in the format that will be delivered to the topic."

> 3. support tuningConfig now by the advanced options. Setting ioConfig is not optional, it must be supported.

- I think we need to separate the areas that go into ioConfig / tuniningConfig in druid ingestion spec.

**Comment by minhyun2** [comment]
@kyungtaak  If the Kafka sample data does not exist, I will modify the guide text as shown in the screenshot below.
metatron_Discovery

**Comment by minhyun2** [comment]
run build
deploy to 4

**Pull request merged**
