### PR TITLE
F#1825 map chart tooltip

### PR DESCRIPTION
**Pull request by choonglee170924**
### Description
1. When the spatial analysis is executed, the value information of the tooltip is displayed differently.
2. If choropleth is the default value, no value information is displayed in the tooltip

**Related Issue** :  #1825 

### How Has This Been Tested?
1. Go to mapchart
2. Click on spatial analysis
3. See error

image

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alchan-lee** [comment]
run build
deploy to 1

**Comment by kyungtaak** [comment]
@choonglee170924 Please check this out!!!!!!!!!!!!!!!!!!!!
image

**Comment by kyungtaak** [comment]
@esezin In this case, should be the "count" value in the tooltip?
image

**Comment by choonglee170924** [comment]
> @choonglee170924 Please check this out!!!!!!!!!!!!!!!!!!!!
> image

@kyungtaak I would appreciate if you check this out too.
How would like me to show if the response is null.
스크린샷 2019-04-12 오후 6 36 52

**Comment by esezin** [comment]
@choonglee170924 @sting009 
count가 기본값인 경우에는 표시, aggregate by가 선택된 경우에는 비표시 처리하면 더 명확할 것 같습니다.

**Comment by kyungtaak** [comment]
run build
deploy to 1

**Comment by kyungtaak** [comment]
run build
deploy to 1

**Comment by alchan-lee** [comment]
run build
deploy to 1

**Comment by kyungtaak** [comment]
run build
deploy to 1

**Comment by kyungtaak** [comment]
run build
deploy to 1

**Pull request merged**
