### PR TITLE
fix engine server list initialization

### PR DESCRIPTION
**Pull request by minhyun2**
### Description

Fix engine server list initialization

**Related Issue** : 

### How Has This Been Tested?

1. After installing the Druid cluster, check the list of Druid clusters on the Engine Monitoring Overview screen.
2. Check the engine server list by setting the URL of Druid's broker, overlord, and coordinator to different clusters.
3. Check the engine server list by setting the URL of Druid's historical, middleManager to different clusters.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 3

**Comment by minhyun2** [comment]
deploy to 3

**Comment by minhyun2** [comment]
deploy to 3

**Comment by minhyun2** [comment]
deploy to 3

**Comment by ufoscw** [comment]
deploy to 3

**Pull request merged**
