### PR TITLE
Fn fix extension dbtype workbench

### PR DESCRIPTION
**Pull request by sting009**
### Description

워크벤치 생성시 DB type에 extension type이 나오지 않는 부분을 수정합니다. 

**Related Issue** : 통합테스트 

### How Has This Been Tested?

1. 워크스페이스에서 워크벤치 생성버튼을 클릭합니다.
2. DB 타입 select box를 선택하여, extension type의 내용이 표시 되는지 확인합니다. 

#### Need additional checks?
DB타입을 변경했을경우 정상적으로 목록이 뜨는지 확인합니다. 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 6

**Comment by ufoscw** [comment]
@sting009 
Parameter error when selecting DB type
DevTools_-_metatron-web-04_8190_app_v2_index_html_및_metatron_Discovery

**Comment by sting009** [comment]
@ufoscw 
image

Fixed parmater type implemntor

**Comment by ufoscw** [comment]
run build
deploy to 6

**Pull request merged**
