### PR TITLE
F#1043 fix missing database selectbox

### PR DESCRIPTION
**Pull request by paigechoi**
### Description

Add missing database select box in dataset creation (query)

**Related Issue** : 

#1043 

### How Has This Been Tested?

Dataset tab -> create db type dataset -> 
image
Check if you can see the select box in query tab

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### Additional Context
Check with staging db type as well

### CODE REVIEW

**Comment by paigechoi** [comment]
Need to add select box in staging db too

**Comment by joohokim1** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
Error message is not appropriate.
dataprep - invalid connection

Datasource page looks like this.
datasource - invalid query

**Comment by paigechoi** [comment]
@joohokim1 Fixed

**Comment by paigechoi** [comment]
@joohokim1 Fixed

**Comment by mh0203** [comment]
run build
deploy to 1

**Comment by mh0203** [comment]
run build
deploy to 1

**Comment by mh0203** [comment]
run build
deploy to 1

**Comment by joohokim1** [comment]
run build
deploy to 4

**Comment by joohokim1** [comment]
run build
deploy to 4

**Pull request merged**
