### PR TITLE
#3763 hide loading in embedded

### PR DESCRIPTION
**Pull request by eltriny**
### Description

hide loading in embedded

**Related Issue** : #3763 

### How Has This Been Tested?

1. Open the dashboard with the following URL form.
    ~/app/v2/embedded/dashboard/frag#[dashboardId]
2. Check if loading is displayed when another dashboard is launched in the same form.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Comment by minhyun2** [comment]
deploy to 2

**Review by minhyun2 — APPROVED** [review]

**Review by ufoscw — APPROVED** [review]

**Pull request merged**
