### PR TITLE
F#2806 exploration catalog css bug

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

exploration css bug
**Related Issue** : 
#2806 

### How Has This Been Tested?

1. Exploration -> Data 
2. In LNB check selected catalog's bold feature works properly
3. Check folding icon toggle properly
4. Check folding icon's tooltip shows properly
5. check New or Update and My Favorite list shows properly
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 4

**Comment by ufoscw** [comment]
@thinkcsww 
1. There is a console error.
DevTools_-_52_231_153_96_8188_app_v2_exploredata_view

2. please change folding button's tooltip
"Fold" / "Unfold"

**Comment by thinkcsww** [comment]
@ufoscw 
1. I think the reason of error is there is no tags in api result.
Can you check this please? 
image

**Comment by ufoscw** [comment]
@thinkcsww 
The API contains tags.
Untagged data may exist.
Please enter the defense code for the untagged data.

**Comment by thinkcsww** [comment]
@ufoscsw
Modified

**Comment by ufoscw** [comment]
deploy to 4

**Comment by ufoscw** [comment]
@thinkcsww 
same console error occurred in "my favorite" list.

**Comment by thinkcsww** [comment]
@ufoscw 
Sorry, Modified again

**Comment by ufoscw** [comment]
deploy to 4

**Pull request merged**
