### PR TITLE
#2680 improve engine monitoring ui

### PR DESCRIPTION
**Pull request by minhyun2**
### Description
Improve engine monitoring ui

**Related Issue** : #2680 

### How Has This Been Tested?

Go to Engine monitoring
1. Select an interval to see if auto refresh is enabled.
2. Check the segment count.
3. Check the task, supervisor, and remote worker instant search on the Ingestion tab.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
run build
deploy to 3

**Comment by minhyun2** [comment]
run build
deploy to 3

**Comment by minhyun2** [comment]
run build
deploy to 3

**Comment by minhyun2** [comment]
run build
deploy to 3

**Comment by minhyun2** [comment]
run build
deploy to 3

**Comment by minhyun2** [comment]
run build
deploy to 3

**Comment by ufoscw** [comment]
@minhyun2 
Missing paging selection when search keyword changes.
metatron_Discovery

**Comment by minhyun2** [comment]
run build
deploy to 3

**Comment by kyungtaak** [comment]
@minhyun2 
- datetime range filter not working.
image

- I can still see the misalignment as below.
image

**Comment by minhyun2** [comment]
run build
deploy to 3

**Comment by minhyun2** [comment]
@kyungtaak Fixed to convert and display the user's time zone.

metatron_Discovery

**Pull request merged**
