### PR TITLE
F#1499 readme file change

### PR DESCRIPTION
**Pull request by AnnieHwang**
### Description
최신 readme 내용 반영

**Related Issue** : 

#1499 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alchan-lee** [comment]
@kyungtaak 
👇 요 부분을 뺐으면 하는데 어떻게 생각하시나요? 
image

**Comment by ucrystal** [comment]
Strength에서 세번째 내용(Intuitive UI)이 두번째와 겹치는 느낌이라서 API로 서비스화한다는 내용으로 바꾸겠습니다.

**Comment by kyungtaak** [comment]
@ucrystal I think Hangul widget names and dashboard name named prefix "copy of" also need to be modified.

**Comment by kyungtaak** [comment]
@AnnieHwang @ucrystal 그리고 "Metatron in Chinese" 가 꼭 들어가야하나요?' ;;;

**Comment by kyungtaak** [comment]
@alchan-lee need to remove the section for geoserver.

**Comment by ucrystal** [comment]
@kyungtaak 넵 좋습니다~! 말씀해주신 대로 반영하겠습니다.

**Pull request merged**
