### PR TITLE
F#2496 show message for error case

### PR DESCRIPTION
**Pull request by ksparknot**
### Description
When user uploads a wrong formatted file, error message should be shown.
about unsupported file or invalid format

**Related Issue** : 
[#2496 ](https://github.com/metatron-app/metatron-discovery/issues/2496)

### How Has This Been Tested?
1. upload an unsupported file like .json
2. upload a file has invalid format. (has no metaId and metaName)

error message should be shown

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ksparknot** [comment]
run build
deploy to 5

**Comment by joohokim1** [comment]
@ksparknot We need some approvements:
1. If we can read as an CSV, then upload and show it in preview page, otherwise show an error message.
2. If a mandatory column (like frMetaName) is missing, then show what should be done and disable the "Next" or "Done" button.

**Comment by kyungtaak** [comment]
run build
deploy to 1

**Comment by kyungtaak** [comment]
@ksparknot Could you upload sample files for testing ?

**Comment by joohokim1** [comment]
@kyungtaak We found that this PR is rather different from the UX design. So I'm closing this. Sorry for taking your time. I'll upload the sample files in the later PR.

**Pull request closed without merging**
