### PR TITLE
F#1644 uri type dataset support

### PR DESCRIPTION
**Pull request by ksparknot**
### Description

Now we support file datasets of URI type.
The URI type will work much like the upload type.

**Related Issue** : 

[#1644](https://github.com/metatron-app/metatron-discovery/issues/1644)

### How Has This Been Tested?

1. create a dataset of URI type and see the details
2. create a wrangled dataset and see the details
3. create a snapshot and see the details
It should work well in the whole process.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ksparknot** [comment]
run build
deploy to 4

**Comment by minjung-cho** [comment]
아래 내용 확인 부탁드립니다. 
1. Validation check --> Load data (한번 변경되었습니다.)
2. URL을 입력하지 않고 Load data 나 Next를 눌렀을 때, URL 입력창 쪽에 Required 문구가 나타나야 합니다. 현재 Load data 버튼 옆에 뜨고 있습니다.
3. 데이터 미리보기가 나오지 않는 상황에서는 Advanced setting UI가 보이지 않는 것이 좋습니다.

이슈에 첨부한 스크린샷으로 설명이 부족할 수 있으니, 위키 기획서 참고 부탁드립니다~

**Comment by ksparknot** [comment]
run build
deploy to 4

**Comment by joohokim1** [comment]
run build
deploy to 4

**Comment by ksparknot** [comment]
run build
deploy to 4

**Comment by ksparknot** [comment]
run build
deploy to 4

**Comment by ksparknot** [comment]
run build
deploy to 4

**Comment by joohokim1** [comment]
run build
deploy to 4

**Pull request merged**
