### PR TITLE
#3774 add org_code column to tenant entity

### PR DESCRIPTION
**Pull request by ufoscw**
### Description
Injecting org_code into Tenant Managed Entity

**Related Issue** : #3774 

### How Has This Been Tested?
1. Check whether org_code column is created in Datasource, DataConnection, RoleDirectory, RoleSet, and ActivityStream tables
2. Check if data is updated in user_org_member table when user or group is created or deleted
3. When creating Datasource, DataConnection, RoleDirectory, RoleSet Entity, check if the org_code value of the user is included in org_code

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Review by minhyun2 — APPROVED** [review]

**Pull request merged**
