### PR TITLE
F#2758 show more info in column and code table

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

show more info in column and code table
**Related Issue** : 
#2758 

### How Has This Been Tested?

1. Exploration -> Data -> Click Metadata -> Columns tab
2. hover dictionary and codetable and check layer shows properly
3. Management -> Exploration -> metadata -> click metadata  -> column tab
4.hover dictionary and code table and check layer shows properly
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 3

**Comment by ufoscw** [comment]
@thinkcsww 
## Management > Metadata > Detail > Column dtails
1. cannot remove column dictionary.
metatron_Discovery

2. mouse hover layer does not need close button
metatron_Discovery

3. Treat the Text and Magnifier button click events in the same action.
metatron_Discovery

4. Layers does not open or close under certain circumstances
Nov-07-2019 13-59-26

5. There is no ellipsis on code table layer
metatron_Discovery


## Exploration > Data > Detail > Column
1. Ellipsis text is cut off
metatron_Discovery

2. no need underline when mouse over, because click event not assigned
metatron_Discovery

**Comment by thinkcsww** [comment]
@ufoscw 
1-5. What if text in code table layer is too long? break the line?

2.1 what is the meaning of cut off

**Comment by ufoscw** [comment]
@thinkcsww 
1-5. sorry..that is a typo.
no ellipsis -> no tooltip

2-1. sorry..that is a typo again.
should display whole text in tooltip.

**Comment by thinkcsww** [comment]
@ufoscw 
Modified

**Comment by ufoscw** [comment]
deploy to 3

**Comment by ufoscw** [comment]
@thinkcsww 
1-4. Mouse events in the column dictionary still malfunction.
Nov-07-2019 17-14-59

**Comment by thinkcsww** [comment]
@ufoscw 
Modified hover error

**Comment by ufoscw** [comment]
deploy to 3

**Comment by AnnieHwang** [comment]
@thinkcsww This button is the Go To List button, not the History Back button. When moving to Exploration => metadata, the button should move to metadata list screen.
image

**Comment by thinkcsww** [comment]
@AnnieHwang 
Modified button to navigate to metadata list

**Comment by ufoscw** [comment]
deploy to 3

**Comment by AnnieHwang** [comment]
@thinkcsww Check out the code table and dictionary details.

**Comment by AnnieHwang** [comment]
@thinkcsww Check out the code table and dictionary details. The list icon is also implemented as a history-back there.
image

**Comment by thinkcsww** [comment]
@AnnieHwang @ufoscw 
Modified code table, dictionary back button

**Comment by ufoscw** [comment]
deploy to 3

**Pull request merged**
