### PR TITLE
F#1319 fix rename popup

### PR DESCRIPTION
**Pull request by paigechoi**
### Description

Fix validation error when tab button is clicked in rename popup

**Related Issue** : 

#1319 

### How Has This Been Tested?

1 . Modify one column name and click on a part other than the corresponding input box 
   1-1.  The grid is redrawn with new column name if there is no error
   1-2. If column name already exists error message (Already in use)  is shown under the input box 
   1-3. If column name has ` error message (Cannot use back quotes in column name) is shown under the input box 
   1-4. If column name is empty, error message (Column name must not be empty) is shown under the input box
   ** Cannot modify other column name if error message is present

2 . Use tab button to move to other input boxes.
Modify a column name -> click tab button -> cursor must move to next input box (grid must change too)

3 . When any input box has focus enter key can be pressed to apply rename.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by joohokim1** [comment]
run build
deploy to 6

**Comment by paigechoi** [comment]
Found bug closing this issue for now.

**Comment by joohokim1** [comment]
run build
deploy to 2

**Comment by joohokim1** [comment]
run build
deploy to 2

**Comment by joohokim1** [comment]
run build
deploy to 2

**Pull request merged**
