### PR TITLE
#3057 set enginename in dashboard

### PR DESCRIPTION
**Pull request by minhyun2**
### Description

Set enginename in dashboard

**Related Issue** : #3057 

### How Has This Been Tested?

1. Create a datasource.
2. Create a dashboard with the datasource created in the first step and create a chart.
3. Change the name of the datasource created in the first step.
4. Make sure the dashboard looks without errors.

#### Need additional checks?
Check a dashboard with multi datasources

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by kyungtaak** [comment]
deploy to 1

**Pull request merged**
