### PR TITLE
#2602 synchronize css

### PR DESCRIPTION
**Pull request by eltriny**
### Description
Update css to the latest version before applying the theme change feature.

**Related Issue** : #2602 

### How Has This Been Tested?

1. Check if the screen contents are displayed normally.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by kyungtaak** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
metatron_Discovery

@eltriny Please check datastorage list page.

**Comment by kyungtaak** [comment]
@eltriny 
1. check download button :  preview in workbench, datasource info in dashboard 
image

2. check text widget 
image

3. It's not related with this issue. but check please.
image

**Comment by ufoscw** [comment]
I'm not sure if it's related to this issue.
1. Popularity background does not match bar
metatron_Discovery

2. Popularity background does not match bar and question mark.
metatron_Discovery

**Comment by kyungtaak** [comment]
@eltriny It's additional issue 
(Administration > Workspapce > List > Detail)
image

**Comment by ksparknot** [comment]
[management]-[data preparation]-[dataflow]-[datafow detail]
the heights of edit rule button and the more button are different

**Comment by minhyun2** [comment]
@eltriny Please check user-defined field
metatron_Discovery

**Comment by minhyun2** [comment]
metatron_Discovery
@eltriny Please check notebook server list page. (management)

**Comment by minhyun2** [comment]
lnb
@eltriny Please check lnb

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
run build
deploy to 2

**Pull request merged**
