### PR TITLE
F#505 Fix checking ingestion status

### PR DESCRIPTION
**Pull request by alchan-lee**
### Description
데이터소스 상세화면에서 적재 상태에 대한 성공 및 실패 상태를 확인하는 process 추가

### Related Issue :

#505

### How Has This Been Tested?
데이터소스 생성
데이터소스 생성 후 상세화면으로 이동
preparing일때 process가 정상적으로 작동하는지 확인
fail일때 process에 어느 상태에서 fail되는지 확인

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### Additional Context
ingestion
progress 단계 아이콘의 위치는 추후 수정하겠습니다

### CODE REVIEW

**Comment by alchan-lee** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by alchan-lee** [comment]
run build
deploy to 2

**Comment by kyungtaak** [comment]
run build
deploy to 2

**Comment by kyungtaak** [comment]
run build
deploy to 1

**Comment by eltriny** [comment]
run build
deploy to 1

**Comment by eltriny** [comment]
run build
deploy to 1

**Comment by kyungtaak** [comment]
run build
deploy to 1

**Comment by kyungtaak** [comment]
run build
deploy to 1

**Comment by kyungtaak** [comment]
run build
deploy to 2

**Comment by kyungtaak** [comment]
run build
deploy to 2

**Comment by kyungtaak** [comment]
run build
deploy to 1

**Pull request merged**
