### PR TITLE
F#2142 lineage view - Metadata Level

### PR DESCRIPTION
**Pull request by ksparknot**
### Description
The lineage view tab is added to the metadata information of mdm
'This tab is still a prototype stage'

**Related Issue** : 
[#2142](https://github.com/metatron-app/metatron-discovery/issues/2142)

### How Has This Been Tested?
1. Create a Wrangled dataset in the following format
( upstream_meta_name, upstream_meta_col_name, downstream_meta_name, downstream_meta_col_name, description )
the metadata name must be a value that actually exists
2. go to the detail view of the wrangled dataset
3. click the make linage button
4. go to [Management - Metadata - Metadata Details - Lineage View tab] 
There will be a lineage diagram for the metadata

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 1

**Comment by ufoscw** [comment]
Complie error 확인 바랍니다.
```
[INFO] WARNING in Empty property 'display' at 28520:43. Ignoring.
[ERROR] ERROR in src/app/meta-data-management/detail/component/lineage-view/lineage-column-view.component.html(17,55): : Property 'closeInfo' is private and only accessible within class 'LineageColumnViewComponent'.
[ERROR] 
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! polaris2-ui@0.0.0 prod: `npm run package-reinstall && node --max_old_space_size=10240 ./node_modules/.bin/ng build --deploy-url /resource/ --output-hashing all --prod --base-href /app/v2/`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the polaris2-ui@0.0.0 prod script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /data1/jenkins/.npm/_logs/2019-07-03T08_46_25_318Z-debug.log
```

**Comment by ksparknot** [comment]
run build
deploy to 6

**Comment by joohokim1** [comment]
run build
deploy to 6

**Comment by joohokim1** [comment]
run build
deploy to 6

**Comment by joohokim1** [comment]
run build
deploy to 6

**Comment by ksparknot** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
Response에는 포함되어 있는데 그려지지 않는 line이 있습니다. 
  "연임테스트03" -> "연임테스트"
  "test_nfl" -> "연임테스트"

* response
DevTools_-_52_231_184_135_8186_app_v2_management_metadata_metadata_32530880-4bf9-42f5-850d-2a8f41b456cf

* lineage
metatron_Discovery

**Comment by ufoscw** [comment]
run build
deploy to 2

**Pull request merged**
