### PR TITLE
fn-fix_mdm_metadata_edit_error

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

fix edit name and description not working if type is stagedb or database
**Related Issue** : 

METATRON-3022

### How Has This Been Tested?

1.Management-> Explore data -> Metadata
2. click list item
3. check edit name and description is working whatever metadata data type is
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by kyungtaak** [comment]
run build
deploy to 6

**Comment by kyungtaak** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
@thinkcsww 
The height and width of the textarea do not match the right button.
metatron_Discovery

**Comment by thinkcsww** [comment]
@ufocsw
2. what text should be displayed when there is no description value ? No description? 
I check planning book but there is no guide.

**Comment by ufoscw** [comment]
@thinkcsww 
If description is undefined, the same message as for empty value is displayed.
"No Description"

**Comment by thinkcsww** [comment]
@ufoscw 
Sorry, i misunderstood
Modified

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
@thinkcsww 
Please check Korean resource bundle
metatron_Discovery

**Comment by thinkcsww** [comment]
@minhyun2 
Modified

**Pull request merged**
