### PR TITLE
#3604 added grid alignment

### PR DESCRIPTION
**Pull request by eltriny**
### Description

It is inconvenient because there is no grid alignment function available to users.

**Related Issue** : #3604 

### How Has This Been Tested?

Click the column at the bottom of the top of the grid to see if it is sorted.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Review by minhyun2 — APPROVED** [review]

**Review by ufoscw — APPROVED** [review]

**Pull request merged**
