### PR TITLE
F#875 monitoring cancelled & running status

### PR DESCRIPTION
**Pull request by paigechoi**
### Description

Show cancelled and running in different font (job log, log statistics)

**Related Issue** : 

#875 

### How Has This Been Tested?

Log statistics -> check cancelled, running status
Log statistics -> log statistics detail   check cancelled, running status
Job log ->  check cancelled, running status
Job log detail ->  check cancelled, running status
image

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alchan-lee** [comment]
run build
deploy to 5

**Comment by ufoscw** [comment]
run build
deploy to 5

**Comment by alchan-lee** [comment]
run build
deploy to 5

**Comment by ufoscw** [comment]
run build
deploy to 5

**Comment by alchan-lee** [comment]
run build
deploy to 5

**Pull request merged**
