### PR TITLE
Fn fix codetable,dictionary time filter error

### PR DESCRIPTION
**Pull request by thinkcsww**
### Description

Fix code table, column dictionary time filter
**Related Issue** : 

### How Has This Been Tested?

1. Management -> Exploration -> Code table -> check time filter works well
2. Management -> Exploration -> Column dictionary -> check time filter works ell
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by thinkcsww** [comment]
@ufoscw 
When i choose only current time or only past time there is no more error.
However filter seems not wokring well. 
In the case of choosing only one date every data is returned as a response

image
image

**Comment by ufoscw** [comment]
@thinkcsww 
ok. i will fix it.

and please change label in ColumnDictionary and Code Table's filter.
Created Date -> Update Date
metatron_Discovery

**Comment by thinkcsww** [comment]
@ufoscw
Modified

**Comment by ufoscw** [comment]
deploy to 4

**Pull request merged**
