### PR TITLE
#2240 improve notebook server list ui

### PR DESCRIPTION
**Pull request by minhyun2**
### Description
1. improve notebook server list ui
2. improve notebook connection exception handler

**Related Issue** : #2240 

### How Has This Been Tested?
Management - Notebook - Notebook Server
04__UI_UX_기획_산출물_-_metatron_-_WIKI_Home

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by alchan-lee** [comment]
Jul-23-2019 12-35-10

@minhyun2 sorry but please check the sorting icon

**Comment by minhyun2** [comment]
run build
deploy to 2

**Pull request merged**
