### PR TITLE
F#3744 fix grid error

### PR DESCRIPTION
**Pull request by eltriny**
### Description
1. The fixed area to the left of the grid is not fixed.
2. If there are quotation marks in the column name, the grid is broken.
3. Columns overlap when resizing the grid.

**Related Issue** : #3744 

### How Has This Been Tested?
1. Create a grid.
2. Check that the left fixed area is fixed when you cross the grid horizontally.
2. If there are quotation marks in the column name, check if the grid is displayed normally.
3. Check that the columns are displayed without overlapping when resizing the grid.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Comment by ufoscw** [comment]
deploy to 2

**Review by ufoscw — APPROVED** [review]

**Review by minhyun2 — APPROVED** [review]

**Pull request merged**
