### PR TITLE
#2856 improve mdm screen admin

### PR DESCRIPTION
**Pull request by eltriny**
### Description

1. Tab order changed ('Column Scheme' first, 'Data Grid' next)
2. Add data type beside data name (in metadata detail page)
3. UI align issue (in metadata detail page) - a publishing issue
4. Metadata's description must be up to 2000 characters - a development issues
5. UX change (Metadata details => Code table detail => Code table popup, Metadata details => Column dictionary detail => Column dictionary popup)

**Related Issue** : #2856 

### How Has This Been Tested?

Check if the screen is displayed normally.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 6

**Comment by minhyun2** [comment]
@eltriny 
4. Metadata's description must be up to 2000 characters - a development issues
If you enter more than 2000 characters in the description, the validation check will work normally.
However, if you click the Cancel button, it looks like it is saved. When you refresh, no data is saved.

metadata

**Comment by ufoscw** [comment]
@eltriny 
1. Column Dictionary Detail Layer
metatron_Discovery

2. Code Table Detail Layer
metatron_Discovery

**Comment by eltriny** [comment]
@minhyun2 @ufoscw 
Modified

**Comment by ufoscw** [comment]
deploy to 6

**Pull request merged**
