### PR TITLE
Fixed missing unionAll query spec

### PR DESCRIPTION
**Pull request by kyungtaak**
### Description
We did not reflect the query to check for similarities in the engine and applied it!

**Related Issue** : #2060 

### How Has This Been Tested?
1. Create a dashboard.
2. In the creation step, select one data source.
3. Select the selected data source and click the "Manage Schema" tab.
4. Click "Add datasource to join".
5. On the Join view, select the data source within the "Datasource to join" panel
6. If there is a column similarity, enter the column with the highest similarity score in the Join keys.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by kyungtaak** [comment]
run build
deploy to 4

**Comment by ufoscw** [comment]
In the data preview of the joined table, I get the following error.

*request
```
{
   "dataSource":{
      "joins":[
         {
            "keyPair":{
               "Col_2":"Category"
            },
            "id":"ds-gis-37",
            "name":"sales_geo",
            "type":"LEFT_OUTER",
            "joinAlias":"join_1",
            "engineName":"sales_geo"
         }
      ],
      "temporary":false,
      "id":"316a82d0-8ace-428f-9b5e-c9014a96f5f5",
      "name":"sales_join",
      "uiDescription":"",
      "type":"mapping",
      "connType":"ENGINE",
      "engineName":"sales_join"
   },
   "filters":[

   ],
   "projections":[

   ],
   "limits":{
      "limit":10000000,
      "sort":[

      ]
   },
   "preview":true,
   "metaQuery":true
}
```

* response
```
{  
   "code":"EG0001",
   "message":"Fail to process response : [{\"error\":\"Unknown exception\",\"errorMessage\":\"handleSourceQuery\",\"errorClass\":\"java.lang.UnsupportedOperationException\",\"errorStack\":[\"io.druid.query.QueryToolChest.handleSubQuery(QueryToolChest.java:318)\",\"io.druid.server.ClientQuerySegmentWalker.makeRunner(ClientQuerySegmentWalker.java:103)\",\"io.druid.server.ClientQuerySegmentWalker.getQueryRunnerForIntervals(ClientQuerySegmentWalker.java:88)\",\"io.druid.query.spec.MultipleIntervalSegmentSpec.lookup(MultipleIntervalSegmentSpec.java:66)\",\"io.druid.query.BaseQuery.run(BaseQuery.java:284)\",\"io.druid.server.QueryResource.doPost(QueryResource.java:257)\",\"sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)\",\"sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\",\"java.lang.reflect.Method.invoke(Method.java:498)\",\"com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)\",\"com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)\",\"com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)\",\"... more\"],\"host\":\"metatron-web-05:8082\",\"serviceName\":\"druid/broker\"}]",
   "details":"QueryTimeExcetpion: [{\"error\":\"Unknown exception\",\"errorMessage\":\"handleSourceQuery\",\"errorClass\":\"java.lang.UnsupportedOperationException\",\"errorStack\":[\"io.druid.query.QueryToolChest.handleSubQuery(QueryToolChest.java:318)\",\"io.druid.server.ClientQuerySegmentWalker.makeRunner(ClientQuerySegmentWalker.java:103)\",\"io.druid.server.ClientQuerySegmentWalker.getQueryRunnerForIntervals(ClientQuerySegmentWalker.java:88)\",\"io.druid.query.spec.MultipleIntervalSegmentSpec.lookup(MultipleIntervalSegmentSpec.java:66)\",\"io.druid.query.BaseQuery.run(BaseQuery.java:284)\",\"io.druid.server.QueryResource.doPost(QueryResource.java:257)\",\"sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)\",\"sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\",\"java.lang.reflect.Method.invoke(Method.java:498)\",\"com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)\",\"com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)\",\"com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)\",\"... more\"],\"host\":\"metatron-web-05:8082\",\"serviceName\":\"druid/broker\"}]"
}
```

**Comment by kyungtaak** [comment]
@ufoscw This issue may be a problem with datasource that contain geometry columns. I will manage this issue separately.

**Comment by AnnieHwang** [comment]
@kyungtaak @ufoscw If you preview the data in the column schema popup after joining datasources, an infinite loop will occur and you will get a script error.
image

**Pull request merged**
