### PR TITLE
#1231 Show appropriate error message in join popup

### PR DESCRIPTION
**Pull request by paigechoi**
### Description

Fix hard to read long error message alert in join popup 

**Related Issue** : 

#1231 

### How Has This Been Tested?

Ran locally
Check #1231 For test instructions

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by kyungtaak** [comment]
run build
deploy to 5

**Comment by kyungtaak** [comment]
@paigechoi please, check this build error.

**Comment by deidera08** [comment]
@paigechoi @kyungtaak 
오류가 발생합니다. 확인 부탁드리겠습니다.
스크린샷 2019-05-13 오후 4 39 40

오류문구:
QueryTimeExcetpion: [{"error":"Can not deserialize instance of java.lang.String out of START_OBJECT token\n at [Source: HttpInputOverHTTP@737240b; line: 1, column: 99] (through reference chain: java.util.ArrayList[0])"}]

참고로 테스트했던 파일입니다.
[testFile.zip](https://github.com/metatron-app/metatron-discovery/files/3171650/testFile.zip)

**Comment by paigechoi** [comment]
@kyungtaak what kind of build error is it ?

**Comment by alchan-lee** [comment]
run build
deploy to 5

**Comment by alchan-lee** [comment]
run build
deploy to 5

**Comment by alchan-lee** [comment]
@kyungtaak it seems to be a problem with the build server.

@paigechoi 
No problem with this pr, please do not mind it.

**Comment by paigechoi** [comment]
@alchan-lee  Sorry, I've pushed one more commit !

**Comment by alchan-lee** [comment]
run build
deploy to 5

**Comment by alchan-lee** [comment]
run build
deploy to 5

**Comment by deidera08** [comment]
@paigechoi 
추가 수정 부탁드립니다.
에러문구가 상황에 맞지 않는것 같아서 수정 부탁드립니다.
“엔진 호출중 오류가 발생하였습니다.“

**Comment by paigechoi** [comment]
@deidera08 , @alchan-lee error message changed!

**Comment by alchan-lee** [comment]
run build
deploy to 5

**Comment by alchan-lee** [comment]
run build
deploy to 5

**Pull request merged**
