### PR TITLE
#2803 Support custom script for chart widget on dashboard

### PR DESCRIPTION
**Pull request by eltriny**
### Description
There are currently needs for limited event control or some chart reshaping in chart widgets placed on structured dashboards. It is an external alarm transmission when used as a dashboard, especially for monitoring purposes. It may be necessary to add event display control in the chart.

**Related Issue** : #2803 

### How Has This Been Tested?

1. Create a chart on the dashboard.
2. In the view screen, click the Event Trigger button at the top to enter the function.
     example )
```javascript
function main(event) {
  if( event.name === 'InitWidgetEvent' ) {
     event.data.series[0].markPoint = {
                data : [
                    {type : 'max', name: '최대값'},
                    {type : 'min', name: '최소값'}
                ]
            };
     event.data.series[0].markLine = {
                data : [
                    {type : 'average', name: '평균값'}
                ]
            };
     return event.data;
  } else if( event.name === 'SelectionEvent' ) {
    switch( event.data.charAt(0).toLowerCase() ) {
        case "a" :
        case "b" :
            alert( event.data );
            return true;
        case "c" :
            window.open( 'http://www.naver.com' );
            return true;
        default :
            return false;
    }
  } else if( event.name === 'SelectionFilterEvent' ) {
      console.info( event.data );
      return event.data.some( item => {
          return 'Category' === item.field;
      });    
  }   
}

```
3. Check if it works as you entered.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ufoscw** [comment]
deploy to 1

**Comment by AnnieHwang** [comment]
@eltriny I want to implement the function only in the edit mode (except the read mode) and also add animation when the pop opens.

**Comment by eltriny** [comment]
@AnnieHwang 
There was no discussion about saving, so I worked on the view mode
Animation effects took time to work on, so I added the priority feature first.

**Comment by minhyun2** [comment]
deploy to 4

**Comment by AnnieHwang** [comment]
@eltriny 
1. When it is black theme, we want to be the same design as white theme. The screen in the current theme moves when mouse hovering.

2. When a popup will be shown, the mouse cursor will be in the input box.

**Comment by minhyun2** [comment]
@eltriny 
I added it as a custom script in the example.
I clicked on the max value, but Central was selected, not West.
And no values ​​were selected for other charts.
customscript

**Comment by kyungtaak** [comment]
deploy to 4

**Pull request merged**
