### PR TITLE
#2388 support black theme

### PR DESCRIPTION
**Pull request by minhyun2**
### Description
support black theme

**Related Issue** : #2388 

### How Has This Been Tested?

1. Click user photo.
2. Change language and theme
metatron_Discovery

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
@eltriny 
1. disappeared button bg.
metatron_Discovery_및_DevTools_-_dev-discovery_metatron_app_app_v2_index_html

2. disappeared data icon when not selected. (Same for both themes)
metatron_Discovery_및_DevTools_-_dev-discovery_metatron_app_app_v2_index_html

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
@eltriny 
Exploration page's css is broken.
metatron_Discovery

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by ufoscw** [comment]
@eltriny 
please resolve conflicts.

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by AnnieHwang** [comment]
@eltriny Logo will be changed.
image

**Comment by ufoscw** [comment]
run build
deploy to 2

**Comment by AnnieHwang** [comment]
@eltriny Fill in the color when there is no dashboard in a workbook.
image

**Comment by minhyun2** [comment]
run build
deploy to 2

**Comment by minhyun2** [comment]
run build
deploy to 2

**Pull request merged**
