### PR TITLE
#159 Unable to click cancel button and X button when generating metadata

### PR DESCRIPTION
**Pull request by nogah12**
### Description

Hive/StagingDB로 메타데이터 생성시 서버 응답이 느려서 로딩바가 도는 경우 '취소' 버튼과 'X' 버튼을 클릭할 수 없음

**Related Issue** :  #159 

### How Has This Been Tested?

* Go to Metadata
* Click on 'Create metadata'
* Select 'Hive' or 'StagingDB'
* Choose a DB connection and Go to Next
* Choose a Schema and Table
* Try click cancel button or X(exit) button when progress bar is displayed.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project. _it will be added soon_
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document. _it will be added soon_
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ufoscw** [comment]
run build
deploy to 4

**Comment by deidera08** [comment]
우측 상단의 '종료 버튼'나 중앙하단의 '이전 버튼'을 클릭해도 취소되지 않습니다.
metadatatest

**Comment by alchan-lee** [comment]
run build
deploy to 4

**Comment by alchan-lee** [comment]
run build
deploy to 4

**Comment by alchan-lee** [comment]
@nogah12 
컴파일 에러 나고 있습니다.

```
[ERROR] 
[ERROR] ERROR in src/app/common/service/abstract.service.ts(290,38): error TS2345: Argument of type '{ headers: Headers; }' is not assignable to parameter of type '{ headers?: HttpHeaders | { [header: string]: string | string[]; }; observe?: "body"; params?: Ht...'.
[ERROR]   Types of property 'headers' are incompatible.
[ERROR]     Type 'Headers' is not assignable to type 'HttpHeaders | { [header: string]: string | string[]; }'.
[ERROR]       Type 'Headers' is not assignable to type '{ [header: string]: string | string[]; }'.
[ERROR]         Index signature is missing in type 'Headers'.
[ERROR] src/app/common/service/abstract.service.ts(295,39): error TS2339: Property 'message' does not exist on type 'Promise<any>'.
[ERROR] 
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! polaris2-ui@0.0.0 prod: `npm run package-reinstall && node --max_old_space_size=10240 ./node_modules/.bin/ng build --deploy-url /resource/ --output-hashing all --prod --base-href /app/v2/`
[ERROR] npm ERR! Exit status 1
```

**Comment by ufoscw** [comment]
@nogah12 
compile 에러 확인 바랍니다.
우선 PR은 close하겠습니다.

**Pull request closed without merging**
