### PR TITLE
#1442 add color inversion to color template

### PR DESCRIPTION
**Pull request by minhyun2**
### Description

Add color inversion to color template

**Related Issue** : #1442 

### How Has This Been Tested?

1. Go to chart.
2. Modify the color of Measure type by using Color Template.
3. Change the color using Color inversion.
4. See also Map View chart.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by kyungtaak** [comment]
deploy to 1

**Comment by kyungtaak** [comment]
deploy to 6

**Comment by ufoscw** [comment]
deploy to 6

**Comment by ufoscw** [comment]
@minhyun2 
console error occurs.
1. create pie chart
2. apply color inversion
3. save chart.
4. edit pie chart again
5. apply custom color setting to on
6. save chart.
7. change custom color setting to off
8. see error

DevTools_-_52_231_153_96_8190_app_v2_workbook_7c8b073d-2689-4396-a729-b327ae97c3eb

**Comment by minhyun2** [comment]
deploy to 2

**Pull request merged**
