### PR TITLE
#3613 added saving grid width

### PR DESCRIPTION
**Pull request by eltriny**
### Description

It is inconvenient because it cannot be saved after changing the grid width.

**Related Issue** : #3613 

### How Has This Been Tested?

1. Go to the chart creation screen.
2. Draw a grid chart.
3. Change the width and save.
4. Check that the changed width is preserved.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by minhyun2** [comment]
deploy to 1

**Comment by ufoscw** [comment]
deploy to 1

**Review by minhyun2 — APPROVED** [review]

**Review by ufoscw — APPROVED** [review]

**Pull request merged**
